-- Alexa parity v6: brotherhood invitations, combat groups, cooperative actions, feedback.

create table if not exists public.guild_invites (
  id uuid primary key default gen_random_uuid(),
  guild_id uuid not null references public.guilds(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(guild_id,receiver_id)
);
create table if not exists public.combat_groups (
  id uuid primary key default gen_random_uuid(), name text not null check(char_length(name) between 3 and 40),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'open' check(status in ('open','in_battle','closed')),
  created_at timestamptz not null default now()
);
create table if not exists public.combat_group_members (
  group_id uuid not null references public.combat_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('leader','member')),
  joined_at timestamptz not null default now(), primary key(group_id,user_id)
);
create table if not exists public.combat_group_invites (
  id uuid primary key default gen_random_uuid(), group_id uuid not null references public.combat_groups(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(group_id,receiver_id)
);
create table if not exists public.group_battle_actions (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.combat_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  monster_name text not null, damage integer not null check(damage between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.game_feedback (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check(kind in ('feedback','bug')), message text not null check(char_length(message) between 3 and 1000),
  created_at timestamptz not null default now()
);

alter table public.guild_invites enable row level security;
alter table public.combat_groups enable row level security;
alter table public.combat_group_members enable row level security;
alter table public.combat_group_invites enable row level security;
alter table public.group_battle_actions enable row level security;
alter table public.game_feedback enable row level security;

do $$ declare p record; begin for p in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('guild_invites','combat_groups','combat_group_members','combat_group_invites','group_battle_actions','game_feedback') loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename); end loop; end $$;

create policy guild_invites_participants_read on public.guild_invites for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
create policy guild_invites_officer_send on public.guild_invites for insert to authenticated with check(sender_id=auth.uid() and public.has_linked_identity() and exists(select 1 from public.guild_members m where m.guild_id=guild_id and m.user_id=auth.uid() and m.role in ('owner','officer')));
create policy guild_invites_receiver_update on public.guild_invites for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());
-- Replace the earlier permissive self-join rule with owner-or-accepted-invite enforcement.
drop policy if exists guild_members_linked_join on public.guild_members;
drop policy if exists guild_members_secure_join on public.guild_members;
create policy guild_members_secure_join on public.guild_members for insert to authenticated with check(
  user_id=auth.uid() and public.has_linked_identity() and (
    (role='owner' and exists(select 1 from public.guilds g where g.id=guild_id and g.owner_id=auth.uid()))
    or exists(select 1 from public.guild_invites i where i.guild_id=guild_id and i.receiver_id=auth.uid() and i.status='accepted')
  )
);

create policy combat_groups_read on public.combat_groups for select to authenticated using(true);
create policy combat_groups_create on public.combat_groups for insert to authenticated with check(owner_id=auth.uid() and public.has_linked_identity());
create policy combat_groups_owner_update on public.combat_groups for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy combat_members_read on public.combat_group_members for select to authenticated using(true);
create policy combat_members_self_join on public.combat_group_members for insert to authenticated with check(
  user_id=auth.uid() and public.has_linked_identity() and (
    (role='leader' and exists(select 1 from public.combat_groups g where g.id=group_id and g.owner_id=auth.uid()))
    or exists(select 1 from public.combat_group_invites i where i.group_id=group_id and i.receiver_id=auth.uid() and i.status='accepted')
  )
);
create policy combat_members_self_leave on public.combat_group_members for delete to authenticated using(user_id=auth.uid());
create policy combat_invites_participants_read on public.combat_group_invites for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
create policy combat_invites_leader_send on public.combat_group_invites for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.combat_group_members m where m.group_id=group_id and m.user_id=auth.uid() and m.role='leader'));
create policy combat_invites_receiver_update on public.combat_group_invites for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());
create policy battle_actions_members_read on public.group_battle_actions for select to authenticated using(exists(select 1 from public.combat_group_members m where m.group_id=group_id and m.user_id=auth.uid()));
create policy battle_actions_members_insert on public.group_battle_actions for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.combat_group_members m where m.group_id=group_id and m.user_id=auth.uid()));
create policy feedback_own_insert on public.game_feedback for insert to authenticated with check(user_id=auth.uid());
create policy feedback_own_read on public.game_feedback for select to authenticated using(user_id=auth.uid());

grant select,insert,update on public.guild_invites to authenticated;
grant select,insert,update on public.combat_groups to authenticated;
grant select,insert,delete on public.combat_group_members to authenticated;
grant select,insert,update on public.combat_group_invites to authenticated;
grant select,insert on public.group_battle_actions to authenticated;
grant usage,select on sequence public.group_battle_actions_id_seq to authenticated;
grant select,insert on public.game_feedback to authenticated;

do $$ begin alter publication supabase_realtime add table public.group_battle_actions; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.guild_invites; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.combat_group_invites; exception when duplicate_object then null; end $$;
