-- v10 secure public/private/custom chat rooms with limits, activation, invites and blacklists.
create table if not exists public.chat_rooms (
 id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null check(char_length(name) between 2 and 40),
 visibility text not null check(visibility in ('public','private','personal')), language text not null default 'en-US',
 owner_id uuid references public.profiles(id) on delete cascade, member_limit integer not null default 50 check(member_limit between 1 and 200),
 activation_minutes integer not null default 5 check(activation_minutes in (0,5,10)), activation_started_at timestamptz, activated_at timestamptz,
 created_at timestamptz not null default now()
);
alter table public.chat_rooms add column if not exists activation_started_at timestamptz;
create table if not exists public.chat_room_members (
 room_id uuid not null references public.chat_rooms(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,
 role text not null default 'member' check(role in ('owner','member')),joined_at timestamptz not null default now(),last_seen timestamptz not null default now(),
 primary key(room_id,user_id)
);
create table if not exists public.chat_room_invites (
 id uuid primary key default gen_random_uuid(),room_id uuid not null references public.chat_rooms(id) on delete cascade,
 sender_id uuid not null references public.profiles(id) on delete cascade,receiver_id uuid not null references public.profiles(id) on delete cascade,
 status text not null default 'pending' check(status in ('pending','accepted','rejected')),created_at timestamptz not null default now(),unique(room_id,receiver_id)
);
create table if not exists public.chat_room_blacklist (
 room_id uuid not null references public.chat_rooms(id) on delete cascade,blocked_user_id uuid not null references public.profiles(id) on delete cascade,
 blocked_by uuid not null references public.profiles(id) on delete cascade,reason text default '',created_at timestamptz not null default now(),primary key(room_id,blocked_user_id)
);
create table if not exists public.chat_room_messages (
 id bigint generated by default as identity primary key,room_id uuid not null references public.chat_rooms(id) on delete cascade,
 sender_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(body) between 1 and 300),
 voice_id text not null default 'boy-1' check(voice_id ~ '^(boy|girl)-([1-9]|10)$'),created_at timestamptz not null default now()
);
create index if not exists chat_room_messages_room_time on public.chat_room_messages(room_id,created_at desc);

alter table public.chat_rooms enable row level security;alter table public.chat_room_members enable row level security;
alter table public.chat_room_invites enable row level security;alter table public.chat_room_blacklist enable row level security;alter table public.chat_room_messages enable row level security;

do $$ declare p record;begin for p in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('chat_rooms','chat_room_members','chat_room_invites','chat_room_blacklist','chat_room_messages') loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename);end loop;end$$;

create or replace function public.can_access_chat_room(target_room uuid)
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from chat_rooms r where r.id=target_room and (r.visibility='public' or r.owner_id=auth.uid() or exists(select 1 from chat_room_members m where m.room_id=r.id and m.user_id=auth.uid()) or exists(select 1 from chat_room_invites i where i.room_id=r.id and i.receiver_id=auth.uid() and i.status in ('pending','accepted'))));
$$;grant execute on function public.can_access_chat_room(uuid) to authenticated;

create policy rooms_visible on public.chat_rooms for select to authenticated using(public.can_access_chat_room(id));
create policy rooms_owner_delete on public.chat_rooms for delete to authenticated using(owner_id=auth.uid());
create policy rooms_owner_update on public.chat_rooms for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy members_visible on public.chat_room_members for select to authenticated using(public.can_access_chat_room(room_id));
create policy members_self_leave on public.chat_room_members for delete to authenticated using(user_id=auth.uid() and role<>'owner');
create policy invites_participants on public.chat_room_invites for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
create policy invites_owner_send on public.chat_room_invites for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_rooms r where r.id=room_id and r.owner_id=auth.uid()));
create policy invites_receiver_update on public.chat_room_invites for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());
create policy blacklist_visible on public.chat_room_blacklist for select to authenticated using(blocked_user_id=auth.uid() or exists(select 1 from public.chat_rooms r where r.id=room_id and r.owner_id=auth.uid()));
create policy blacklist_owner_add on public.chat_room_blacklist for insert to authenticated with check(blocked_by=auth.uid() and exists(select 1 from public.chat_rooms r where r.id=room_id and r.owner_id=auth.uid()));
create policy blacklist_owner_remove on public.chat_room_blacklist for delete to authenticated using(exists(select 1 from public.chat_rooms r where r.id=room_id and r.owner_id=auth.uid()));
create policy room_messages_visible on public.chat_room_messages for select to authenticated using(exists(select 1 from public.chat_room_members m where m.room_id=room_id and m.user_id=auth.uid()));
create policy room_messages_send on public.chat_room_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_room_members m where m.room_id=room_id and m.user_id=auth.uid()) and not exists(select 1 from public.chat_room_blacklist b where b.room_id=room_id and b.blocked_user_id=auth.uid()));

grant select,update,delete on public.chat_rooms to authenticated;grant select,delete on public.chat_room_members to authenticated;
grant select,insert,update on public.chat_room_invites to authenticated;grant select,insert,delete on public.chat_room_blacklist to authenticated;
grant select,insert on public.chat_room_messages to authenticated;grant usage,select on sequence public.chat_room_messages_id_seq to authenticated;

-- Default permanent public rooms.
insert into public.chat_rooms(slug,name,visibility,language,owner_id,member_limit,activation_minutes,activated_at) values
 ('world','World Chat','public','en-US',null,200,0,now()),('trade','Trade Chat','public','en-US',null,100,0,now()),
 ('help','Help & New Heroes','public','en-US',null,100,0,now()),('french','Discussion Française','public','fr-FR',null,100,0,now())
on conflict(slug) do nothing;

create or replace function public.ensure_personal_chat_room()
returns uuid language plpgsql security definer set search_path=public as $$declare rid uuid;hero text;begin
 if auth.uid() is null then raise exception 'Authentication required';end if;select display_name into hero from profiles where id=auth.uid();
 select id into rid from chat_rooms where owner_id=auth.uid() and visibility='personal';
 if rid is null then insert into chat_rooms(slug,name,visibility,language,owner_id,member_limit,activation_minutes,activated_at) values('private-'||auth.uid()::text,coalesce(hero,'Hero')||'''s Private Chat','personal','en-US',auth.uid(),1,0,now()) returning id into rid;insert into chat_room_members(room_id,user_id,role) values(rid,auth.uid(),'owner');end if;return rid;end$$;

create or replace function public.create_custom_chat_room(room_name text,room_visibility text,max_users integer,wait_minutes integer)
returns uuid language plpgsql security definer set search_path=public as $$declare rid uuid;clean_slug text;begin
 if auth.uid() is null or not has_linked_identity() then raise exception 'Link Google before creating a room';end if;
 if room_visibility not in ('public','private') then raise exception 'Visibility must be public or private';end if;
 clean_slug='custom-'||substr(replace(gen_random_uuid()::text,'-',''),1,12);
 insert into chat_rooms(slug,name,visibility,owner_id,member_limit,activation_minutes,activation_started_at) values(clean_slug,left(trim(room_name),40),room_visibility,auth.uid(),greatest(2,least(200,max_users)),case when wait_minutes=10 then 10 else 5 end,now()) returning id into rid;
 insert into chat_room_members(room_id,user_id,role) values(rid,auth.uid(),'owner');return rid;end$$;

create or replace function public.join_chat_room(target_room uuid)
returns boolean language plpgsql security definer set search_path=public as $$declare r chat_rooms%rowtype;members integer;previous_seen timestamptz;begin
 select * into r from chat_rooms where id=target_room;select last_seen into previous_seen from chat_room_members where room_id=target_room and user_id=auth.uid();if r.id is null then raise exception 'Room not found';end if;
 if exists(select 1 from chat_room_blacklist where room_id=r.id and blocked_user_id=auth.uid()) then raise exception 'You are blacklisted from this room';end if;
 if r.visibility='personal' and r.owner_id<>auth.uid() then raise exception 'Personal rooms are owner-only';end if;
 if r.activated_at is null and r.owner_id<>auth.uid() then raise exception 'Room is not active yet';end if;
 if r.visibility='private' and r.owner_id<>auth.uid() and not exists(select 1 from chat_room_invites where room_id=r.id and receiver_id=auth.uid() and status='accepted') then raise exception 'Private-room invitation required';end if;
 select count(*) into members from chat_room_members where room_id=r.id;if members>=r.member_limit and not exists(select 1 from chat_room_members where room_id=r.id and user_id=auth.uid()) then raise exception 'Room is full';end if;
 if r.owner_id=auth.uid() and r.activated_at is null and (previous_seen is null or previous_seen<now()-interval '90 seconds') then update chat_rooms set activation_started_at=now() where id=r.id;end if;
 insert into chat_room_members(room_id,user_id,role,last_seen) values(r.id,auth.uid(),case when r.owner_id=auth.uid() then 'owner' else 'member' end,now()) on conflict(room_id,user_id) do update set last_seen=now();return true;end$$;

create or replace function public.chat_room_heartbeat(target_room uuid)
returns jsonb language plpgsql security definer set search_path=public as $$declare r chat_rooms%rowtype;occupancy integer;previous_seen timestamptz;begin
 if not exists(select 1 from chat_room_members where room_id=target_room and user_id=auth.uid()) then raise exception 'Join the room before sending heartbeat';end if;
 select last_seen into previous_seen from chat_room_members where room_id=target_room and user_id=auth.uid();
 select * into r from chat_rooms where id=target_room;
 if r.owner_id=auth.uid() and r.activated_at is null and (r.activation_started_at is null or previous_seen is null or previous_seen<now()-interval '90 seconds') then update chat_rooms set activation_started_at=now() where id=r.id returning * into r;end if;
 update chat_room_members set last_seen=now() where room_id=target_room and user_id=auth.uid();
 if r.owner_id=auth.uid() and r.activated_at is null and now()>=r.activation_started_at+make_interval(mins=>r.activation_minutes) then update chat_rooms set activated_at=now() where id=r.id returning * into r;end if;
 select count(*) into occupancy from chat_room_members where room_id=target_room and last_seen>now()-interval '2 minutes';return jsonb_build_object('users',occupancy,'activated',r.activated_at is not null,'activation_minutes',r.activation_minutes,'activation_started_at',r.activation_started_at);end$$;

create or replace function public.blacklist_chat_user(target_room uuid,target_user uuid,block_reason text default '')
returns boolean language plpgsql security definer set search_path=public as $$begin
 if not exists(select 1 from chat_rooms where id=target_room and owner_id=auth.uid()) then raise exception 'Only the room owner can blacklist users';end if;
 if target_user=auth.uid() then raise exception 'Owner cannot blacklist self';end if;
 insert into chat_room_blacklist(room_id,blocked_user_id,blocked_by,reason) values(target_room,target_user,auth.uid(),left(block_reason,200)) on conflict(room_id,blocked_user_id) do update set reason=excluded.reason,blocked_by=auth.uid(),created_at=now();
 delete from chat_room_members where room_id=target_room and user_id=target_user;return true;end$$;

grant execute on function public.ensure_personal_chat_room() to authenticated;grant execute on function public.create_custom_chat_room(text,text,integer,integer) to authenticated;
grant execute on function public.join_chat_room(uuid) to authenticated;grant execute on function public.chat_room_heartbeat(uuid) to authenticated;grant execute on function public.blacklist_chat_user(uuid,uuid,text) to authenticated;

do $$ begin alter publication supabase_realtime add table public.chat_room_messages;exception when duplicate_object then null;end$$;
do $$ begin alter publication supabase_realtime add table public.chat_room_members;exception when duplicate_object then null;end$$;
