-- v16 generic realtime sessions for accessible board/card games.
create table if not exists public.game_hall_sessions (
 id uuid primary key default gen_random_uuid(),game_type text not null check(game_type in ('ludo','snakes','chess','carrom','blackjack')),
 name text not null,owner_id uuid not null references profiles(id) on delete cascade,max_players integer not null check(max_players between 1 and 4),
 state jsonb not null default '{}'::jsonb,version integer not null default 0,status text not null default 'waiting' check(status in ('waiting','playing','finished')),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.game_hall_members(session_id uuid not null references game_hall_sessions(id) on delete cascade,user_id uuid not null references profiles(id) on delete cascade,seat integer not null,joined_at timestamptz not null default now(),primary key(session_id,user_id),unique(session_id,seat));
create table if not exists public.game_hall_invites(id uuid primary key default gen_random_uuid(),session_id uuid not null references game_hall_sessions(id) on delete cascade,sender_id uuid not null references profiles(id) on delete cascade,receiver_id uuid not null references profiles(id) on delete cascade,status text not null default 'pending' check(status in ('pending','accepted','rejected')),created_at timestamptz not null default now(),unique(session_id,receiver_id));
alter table game_hall_sessions enable row level security;alter table game_hall_members enable row level security;alter table game_hall_invites enable row level security;
do $$declare p record;begin for p in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('game_hall_sessions','game_hall_members','game_hall_invites') loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename);end loop;end$$;
create or replace function public.game_session_member(s uuid)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from game_hall_members where session_id=s and user_id=auth.uid());$$;grant execute on function game_session_member(uuid) to authenticated;
create policy sessions_read on game_hall_sessions for select to authenticated using(owner_id=auth.uid() or game_session_member(id) or status='waiting');create policy sessions_owner_delete on game_hall_sessions for delete to authenticated using(owner_id=auth.uid());
create policy members_read on game_hall_members for select to authenticated using(game_session_member(session_id) or exists(select 1 from game_hall_sessions s where s.id=session_id and s.status='waiting'));
create policy invites_read on game_hall_invites for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());create policy invites_send on game_hall_invites for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from game_hall_sessions s where s.id=session_id and s.owner_id=auth.uid()));create policy invites_update on game_hall_invites for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());
grant select,delete on game_hall_sessions to authenticated;grant select on game_hall_members to authenticated;grant select,insert,update on game_hall_invites to authenticated;
create or replace function public.create_game_hall_session(kind text,session_name text,players integer,initial_state jsonb)
returns uuid language plpgsql security definer set search_path=public as $$declare sid uuid;begin if not has_linked_identity() then raise exception 'Link Google before creating an online game';end if;insert into game_hall_sessions(game_type,name,owner_id,max_players,state) values(kind,left(session_name,60),auth.uid(),greatest(1,least(4,players)),initial_state) returning id into sid;insert into game_hall_members values(sid,auth.uid(),0,now());return sid;end$$;
create or replace function public.join_game_hall_session(sid uuid)
returns integer language plpgsql security definer set search_path=public as $$declare s game_hall_sessions%rowtype;seat_no integer;begin select * into s from game_hall_sessions where id=sid;if s.id is null then raise exception 'Game not found';end if;if s.status<>'waiting' then raise exception 'Game already started';end if;if s.owner_id<>auth.uid() and not exists(select 1 from game_hall_invites where session_id=sid and receiver_id=auth.uid() and status='accepted') then raise exception 'Invitation required';end if;select coalesce(min(x),0) into seat_no from generate_series(0,s.max_players-1)x where not exists(select 1 from game_hall_members m where m.session_id=sid and m.seat=x);if seat_no is null then raise exception 'Game is full';end if;insert into game_hall_members values(sid,auth.uid(),seat_no,now()) on conflict(session_id,user_id) do nothing;return seat_no;end$$;
create or replace function public.update_game_hall_state(sid uuid,expected_version integer,new_state jsonb,new_status text default 'playing')
returns integer language plpgsql security definer set search_path=public as $$declare next_version integer;begin if not game_session_member(sid) then raise exception 'Not a game member';end if;update game_hall_sessions set state=new_state,version=version+1,status=new_status,updated_at=now() where id=sid and version=expected_version returning version into next_version;if next_version is null then raise exception 'Game state changed; refresh and retry';end if;return next_version;end$$;
grant execute on function create_game_hall_session(text,text,integer,jsonb) to authenticated;grant execute on function join_game_hall_session(uuid) to authenticated;grant execute on function update_game_hall_state(uuid,integer,jsonb,text) to authenticated;
do $$begin alter publication supabase_realtime add table game_hall_sessions;exception when duplicate_object then null;end$$;
