-- Black Sword Ultimate multiplayer schema
-- Run once in Supabase Dashboard -> SQL Editor -> New query.
-- Safe to run again: tables and policies are created idempotently where possible.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  player_code text not null unique,
  display_name text not null default 'Wandering Hero',
  level integer not null default 1 check (level between 1 and 999),
  current_location text not null default 'Kaliwasch City',
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.game_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);
create unique index if not exists one_pending_friend_request
  on public.friend_requests (least(sender_id, receiver_id), greatest(sender_id, receiver_id))
  where status in ('pending','accepted');

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  created_at timestamptz not null default now()
);
create index if not exists messages_created_idx on public.messages(created_at desc);
create index if not exists messages_receiver_idx on public.messages(receiver_id, created_at desc);

create table if not exists public.guilds (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 3 and 32),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  rupees bigint not null default 0 check (rupees >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.guild_members (
  guild_id uuid not null references public.guilds(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','officer','member')),
  joined_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 500),
  created_at timestamptz not null default now(),
  check (reporter_id <> reported_id)
);

-- Creates the permanent readable ID when Auth creates a guest or linked account.
create or replace function public.create_player_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  generated_code text;
begin
  loop
    generated_code := 'KND-' || substring(upper(replace(gen_random_uuid()::text, '-', '')) from 1 for 4)
                            || '-' || substring(upper(replace(gen_random_uuid()::text, '-', '')) from 1 for 4);
    exit when not exists (select 1 from public.profiles where player_code = generated_code);
  end loop;
  insert into public.profiles (id, player_code, display_name)
  values (new.id, generated_code, coalesce(nullif(new.raw_user_meta_data->>'display_name',''), 'Wandering Hero'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
after insert on auth.users
for each row execute function public.create_player_profile();

-- True only after an anonymous account is linked to Google or another provider.
create or replace function public.has_linked_identity()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from auth.identities
    where user_id = auth.uid() and provider <> 'anonymous'
  );
$$;
grant execute on function public.has_linked_identity() to authenticated;

alter table public.profiles enable row level security;
alter table public.game_saves enable row level security;
alter table public.friend_requests enable row level security;
alter table public.messages enable row level security;
alter table public.guilds enable row level security;
alter table public.guild_members enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;

-- Recreate named policies so rerunning this file updates security rules.
do $$ declare p record; begin
  for p in select schemaname, tablename, policyname from pg_policies
           where schemaname='public' and tablename in
           ('profiles','game_saves','friend_requests','messages','guilds','guild_members','blocks','reports')
  loop execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename); end loop;
end $$;

-- Profiles contain no email address. Authenticated guests may search safe public profile fields.
create policy profiles_read on public.profiles for select to authenticated using (true);
create policy profiles_update_self on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

create policy saves_own_read on public.game_saves for select to authenticated using (user_id = auth.uid());
create policy saves_own_insert on public.game_saves for insert to authenticated with check (user_id = auth.uid());
create policy saves_own_update on public.game_saves for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy requests_participant_read on public.friend_requests for select to authenticated
  using (sender_id = auth.uid() or receiver_id = auth.uid());
create policy requests_linked_send on public.friend_requests for insert to authenticated
  with check (sender_id = auth.uid() and public.has_linked_identity());
create policy requests_receiver_update on public.friend_requests for update to authenticated
  using (receiver_id = auth.uid()) with check (receiver_id = auth.uid());

-- receiver_id NULL means public chat. Guests can read but linked users alone can send.
create policy messages_visible on public.messages for select to authenticated using (
  receiver_id is null or sender_id = auth.uid() or receiver_id = auth.uid()
);
create policy messages_linked_send on public.messages for insert to authenticated
  with check (sender_id = auth.uid() and public.has_linked_identity());

create policy guilds_read on public.guilds for select to authenticated using (true);
create policy guilds_linked_create on public.guilds for insert to authenticated
  with check (owner_id = auth.uid() and public.has_linked_identity());
create policy guilds_owner_update on public.guilds for update to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy guild_members_read on public.guild_members for select to authenticated using (true);
create policy guild_members_linked_join on public.guild_members for insert to authenticated
  with check (user_id = auth.uid() and public.has_linked_identity());
create policy guild_members_self_leave on public.guild_members for delete to authenticated using (user_id = auth.uid());

create policy blocks_own_read on public.blocks for select to authenticated using (blocker_id = auth.uid());
create policy blocks_own_insert on public.blocks for insert to authenticated with check (blocker_id = auth.uid());
create policy blocks_own_delete on public.blocks for delete to authenticated using (blocker_id = auth.uid());
create policy reports_own_insert on public.reports for insert to authenticated with check (reporter_id = auth.uid());
create policy reports_own_read on public.reports for select to authenticated using (reporter_id = auth.uid());

-- Realtime publication. Ignore duplicate-object errors on reruns.
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.friend_requests;
exception when duplicate_object then null; end $$;

grant usage on schema public to authenticated;
revoke update on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, level, current_location, last_seen) on public.profiles to authenticated;
grant select, insert, update on public.game_saves to authenticated;
revoke update on public.friend_requests from authenticated;
grant select, insert on public.friend_requests to authenticated;
grant update (status, updated_at) on public.friend_requests to authenticated;
grant select, insert on public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;
revoke update on public.guilds from authenticated;
grant select, insert on public.guilds to authenticated;
grant update (name) on public.guilds to authenticated;
grant select, insert, delete on public.guild_members to authenticated;
grant select, insert, delete on public.blocks to authenticated;
grant select, insert on public.reports to authenticated;
