/** Evidence-based command and multiplayer parity layer for documented Alexa features. */
(() => {
    const defaults=()=>({mapNotes:[],puzzles:{},restartPendingUntil:0});
    const ensure=()=>Game.state.parity=Object.assign(defaults(),Game.state.parity||{});
    WorldData.items['sealed letter']={name:'Sealed Letter',type:'document',value:2,desc:'A letter bearing the royal seal. It mentions the Palace advancement ceremony.'};
    WorldData.items['rune message']={name:'Rune Message',type:'document',value:5,desc:'Arcane writing: Press what is hidden, pull what is still, and locked roads will answer.'};
    WorldData.items['wooden sign']={name:'Wooden Sign',type:'document',value:1,desc:'Kaliwasch: east to ruins, west to forest, north to mountains, south to swamp.'};
    WorldData.locations.kaliwasch.items.push('wooden sign','sealed letter');
    WorldData.locations.great_forest_path_7.features.push('hidden button');
    WorldData.locations.endless_cave_18.features.push('ancient lever');
    WorldData.locations.royal_dungeon_12.features.push('runed locked door');

    const oldGet=Game.getSaveData.bind(Game);Game.getSaveData=function(){return{...oldGet(),parity:ensure()};};
    const oldContinue=Game.continueGame.bind(Game);Game.continueGame=function(){let data;try{const r=this.getRoster();data=r.heroes[r.activeHeroId]||JSON.parse(localStorage.getItem(this.state.saveKey));}catch{}oldContinue();this.state.parity=Object.assign(defaults(),data?.parity||{});};

    Game.showFilteredInventory=function(filter='all'){
        const armorTypes=['armor','helmet','gloves','boots'];const categories={weapon:i=>i.type==='weapon',weapons:i=>i.type==='weapon',armor:i=>armorTypes.includes(i.type),armour:i=>armorTypes.includes(i.type),potion:i=>i.type==='potion',potions:i=>i.type==='potion',food:i=>i.type==='food',items:i=>!['weapon','armor','helmet','gloves','boots','potion','food'].includes(i.type),all:()=>true};
        if(filter==='gold'){this.addNarrative(`You carry ${this.state.player.gold} rupees.`,'treasure');return;}
        const pred=categories[filter]||categories.all,items=this.state.inventory.filter(pred),list=document.getElementById('inv-list');list.innerHTML=items.length?items.map(i=>`<div class="inv-item"><span>${this.escapeHTML(i.name)} — ${this.escapeHTML(i.desc||'')}</span><span>x${i.quantity}</span></div>`).join(''):'<p>No matching items.</p>';document.getElementById('inventory-panel').classList.remove('hidden');
    };
    Game.buyQuantity=function(quantity,query){const loc=WorldData.locations[this.state.location],stock=ExpansionData.shopStock[loc?.shop]||[];const entry=stock.find(s=>(WorldData.items[s.id]?.name||s.id).toLowerCase().includes(query.toLowerCase()));quantity=Math.max(1,Math.min(99,quantity||1));if(!loc?.shop||!entry){this.addNarrative('That item is not sold at this location.','system');return;}const cost=entry.price*quantity;if(this.state.player.gold<cost){this.addNarrative(`${quantity} cost ${cost} rupees; you do not have enough.`,'system');return;}this.state.player.gold-=cost;for(let i=0;i<quantity;i++)this.addItemToInventory(entry.id,WorldData.items[entry.id]);this.addNarrative(`Bought ${quantity} ${WorldData.items[entry.id].name} for ${cost} rupees.`,'item');this.save();this.updateHUD();};
    Game.sellQuantity=function(quantity,query){const loc=WorldData.locations[this.state.location],item=this.state.inventory.find(i=>i.name.toLowerCase().includes(query.toLowerCase()));if(!loc?.shop&&this.state.location!=='arcane_enchantery'){this.addNarrative('Sell at a shop or enchantery.','system');return;}if(!item){this.addNarrative('Item not found.','system');return;}quantity=Math.max(1,Math.min(quantity||1,item.quantity));const each=Math.max(1,Math.floor((item.value||item.damage||10)*.35));item.quantity-=quantity;if(item.quantity<=0)this.state.inventory.splice(this.state.inventory.indexOf(item),1);this.state.player.gold+=each*quantity;this.addNarrative(`Sold ${quantity} ${item.name} for ${each*quantity} rupees.`,'treasure');this.save();this.updateHUD();};
    Game.contextList=function(){const loc=WorldData.locations[this.state.location],dirs=['north','west','east','south','up','down'].filter(d=>loc.exits[d]),npcs=(WorldData.npcs[this.state.location]||[]).map(n=>n.name);this.addNarrative(`Directions: ${dirs.join(', ')||'none'}. Features: ${(loc.features||[]).join(', ')||'none'}. Items: ${(loc.items||[]).map(i=>WorldData.items[i]?.name||i).join(', ')||'none'}. People: ${npcs.join(', ')||'none'}.`,'location');};
    Game.topicStatus=function(topic){const p=this.state.player,t=topic.toLowerCase();if(t==='health')this.addNarrative(`Health: ${p.hp}/${p.maxHp} HP; vitality ${p.vit||0}; defense ${p.defense||0}.`,'system');else if(t==='magic')this.addNarrative(`Magic: ${p.mp}/${p.maxMp} MP. Spells: ${p.spells.join(', ')}.`,'magic');else if(t==='skills')this.addNarrative(`Skills: level ${p.level}; STR ${p.str}; DEX ${p.dex}; INT ${p.int}; WIS ${p.wis}; VIT ${p.vit||0}.`,'system');else if(['armor','armour'].includes(t))this.addNarrative(`Armor: ${p.armor||'none'}; defense ${p.defense||0}. Weapon: ${p.weapon||'none'}.`,'item');else this.showStats();};
    Game.readObject=function(query){const item=this.state.inventory.find(i=>i.name.toLowerCase().includes(query.toLowerCase()))||WorldData.items[query.toLowerCase()];if(item?.type==='document')this.addNarrative(`${item.name}: “${item.desc}”`,'location');else this.addNarrative('There is no readable letter, sign, or message by that name.','system');};
    Game.pressMechanism=function(query){const s=ensure(),loc=this.state.location,features=WorldData.locations[loc].features||[];if(/button/.test(query)&&features.some(f=>/button/.test(f))&&!s.puzzles[`${loc}:button`]){s.puzzles[`${loc}:button`]=true;this.state.sacred.groundLoot.push({...WorldData.items['rune message'],id:'rune message',quantity:1});this.addNarrative('A concealed stone panel opens. A Rune Message drops to the ground; type “loot”.','treasure');MusicSystem.playSFX('door');this.save();return;}this.addNarrative('Nothing happens. Examine the location for a mechanism first.','system');};
    Game.useLever=function(){const s=ensure(),loc=this.state.location,features=WorldData.locations[loc].features||[];if(features.some(f=>/lever/.test(f))&&!s.puzzles[`${loc}:lever`]){s.puzzles[`${loc}:lever`]=true;this.state.player.gold+=75;this.addNarrative('The ancient lever opens a mineral cache: 75 rupees awarded.','treasure');MusicSystem.playSFX('door');this.save();return;}this.addNarrative('No unused lever is available here.','system');};
    Game.addMapNote=function(text){const s=ensure();if(!text.trim())return;s.mapNotes.push({location:this.state.location,text:text.trim().slice(0,120),time:Date.now()});s.mapNotes=s.mapNotes.slice(-100);this.addNarrative('Personal map note added.','system');this.save();};
    Game.showMapNotes=function(){const s=ensure();this.addNarrative(s.mapNotes.length?s.mapNotes.map(n=>`${WorldData.locations[n.location]?.name||n.location}: ${n.text}`).join(' | '):'No personal map notes yet.','location');};
    Game.safeRestart=function(){const s=ensure();if(Date.now()>s.restartPendingUntil){s.restartPendingUntil=Date.now()+30000;this.addNarrative('Restart will recreate only the active hero. Type “confirm restart” within 30 seconds. Other heroes are safe.','system');return;}const roster=this.getRoster(),id=roster.activeHeroId;delete roster.heroes[id];roster.activeHeroId=Object.keys(roster.heroes)[0]||null;this.storeRoster(roster);this.state.activeHeroId=null;this.state.pendingHeroId=id;this.addNarrative('Active hero restart confirmed. Create the replacement hero.','system');this.showScreen('char-screen');};
    Game.rescueHero=function(query){const c=this.state.companions.find(x=>x.name.toLowerCase().includes(query.toLowerCase()));if(c&&c.hp<=0){c.hp=Math.ceil(c.maxHp/2);this.addNarrative(`${c.name} is rescued and revived at half health.`,'green-light');this.save();return;}this.addNarrative('No defeated hero or companion by that name needs rescue.','system');};

    Game.showOnlineHeroes=async function(){const heroes=await OnlineSystem.listOnlineHeroes();this.addNarrative(heroes.length?heroes.map(h=>`${h.display_name}, level ${h.level}, ${h.current_location}`).join(' | '):'No other heroes were active in the last ten minutes.','npc');};
    Game.showMultiplayerInvites=async function(){const [b,c]=await Promise.all([OnlineSystem.listBrotherhoodInvites(),OnlineSystem.listCombatGroupInvites()]);this.addNarrative(`Brotherhood invites: ${b.map((x,i)=>`${i+1}. ${x.guild?.name} from ${x.sender?.display_name}`).join('; ')||'none'}. Combat-group invites: ${c.map((x,i)=>`${i+1}. ${x.group?.name} from ${x.sender?.display_name}`).join('; ')||'none'}.`,'npc');this._brotherhoodInvites=b;this._combatInvites=c;};

    // Publish local attack/spell damage to the active online combat group.
    const oldAttack=Game.playerAttack.bind(Game);Game.playerAttack=function(){const e=this.state.enemy,before=e?.hp||0,name=e?.name;oldAttack();const damage=Math.max(0,before-(e?.hp||0));if(name&&damage)OnlineSystem.recordGroupAttack(name,damage);};
    const oldCast=Game.castSpell.bind(Game);Game.castSpell=function(name){const e=this.state.enemy,before=e?.hp||0,monster=e?.name;oldCast(name);const damage=Math.max(0,before-(e?.hp||0));if(monster&&damage)OnlineSystem.recordGroupAttack(monster,damage);};

    const oldCommand=Game.processCommand.bind(Game);Game.processCommand=function(cmd){const c=cmd.toLowerCase().trim();
        const inv=c.match(/^inventory(?:\s+(weapons?|armou?r|potions?|food|items?|gold))?$/);if(inv){this.showFilteredInventory(inv[1]||'all');return;}
        const buy=c.match(/^buy\s+(?:(\d+)\s+)?(.+)$/);if(buy){this.buyQuantity(Number(buy[1]||1),buy[2]);return;}const sell=c.match(/^sell\s+(?:(\d+)\s+)?(.+)$/);if(sell){this.sellQuantity(Number(sell[1]||1),sell[2]);return;}
        if(c==='list'){this.contextList();return;}const st=c.match(/^status(?:\s+(health|skills|magic|attributes|armou?r))?$/);if(st){this.topicStatus(st[1]||'');return;}
        if(c.startsWith('read ')){this.readObject(c.slice(5));return;}if(c.startsWith('press ')){this.pressMechanism(c.slice(6));return;}if(c==='use lever'||c==='pull lever'){this.useLever();return;}
        if(c.startsWith('mark map ')){this.addMapNote(cmd.trim().slice(9));return;}if(c==='map notes'||c==='player map'){this.showMapNotes();return;}
        if(c==='restart'||c==='restart hero'){ensure().restartPendingUntil=0;this.safeRestart();return;}if(c==='confirm restart'){this.safeRestart();return;}if(c.startsWith('rescue ')){this.rescueHero(c.slice(7));return;}
        if(c==='online heroes'||c==='who is online'){this.showOnlineHeroes();return;}if(c==='multiplayer invites'||c==='invitations'){this.showMultiplayerInvites();return;}
        if(c.startsWith('create brotherhood ')){OnlineSystem.createGuild(cmd.trim().slice(19));return;}if(c.startsWith('invite brotherhood ')){OnlineSystem.inviteBrotherhood(cmd.trim().slice(19));return;}
        const ab=c.match(/^accept brotherhood (\d+)$/);if(ab){const i=this._brotherhoodInvites?.[Number(ab[1])-1];if(i)OnlineSystem.respondBrotherhoodInvite(i.id,true);return;}
        if(c.startsWith('create combat group')){OnlineSystem.createCombatGroup(cmd.trim().slice(19).trim()||'Hero Combat Group');return;}if(c.startsWith('invite combat group ')){OnlineSystem.inviteCombatGroup(cmd.trim().slice(20));return;}
        const ac=c.match(/^accept combat group (\d+)$/);if(ac){const i=this._combatInvites?.[Number(ac[1])-1];if(i)OnlineSystem.respondCombatGroupInvite(i.id,true);return;}
        const report=c.match(/^(feedback|report bug|bug report)\s+(.+)$/);if(report){OnlineSystem.sendFeedback(report[1]==='feedback'?'feedback':'bug',report[2]);return;}
        oldCommand(cmd);
    };
    window.AlexaParity={documentedCommands:true};
})();
