/** Secure default, personal, and owner-managed Supabase chat rooms. */
const ChatRooms={
    rooms:[],current:null,messages:[],subscription:null,heartbeatTimer:null,countdownTimer:null,
    async ensureReady(){if(!OnlineSystem.ready)await OnlineSystem.init();if(!OnlineSystem.ready)throw new Error('Online account is still connecting.');},
    async open(){const panel=document.getElementById('chat-rooms-panel'),list=document.getElementById('chat-room-list');panel.classList.remove('hidden');list.innerHTML='<p>Loading World, Trade, Help, French, and Private rooms…</p>';try{await this.ensureReady();const {error}=await OnlineSystem.client.rpc('ensure_personal_chat_room');if(error)throw error;await this.refresh();}catch(e){list.innerHTML=`<p>Chat rooms could not load: ${Game.escapeHTML(e.message)}.</p><p>Run the latest Supabase chat-room migration, then refresh.</p>`;Game.addNarrative(`Chat rooms unavailable: ${e.message}.`,'system');}},
    async refresh(){
        const {data,error}=await OnlineSystem.client.from('chat_rooms').select('*,owner:profiles!chat_rooms_owner_id_fkey(display_name)').order('created_at',{ascending:true});if(error)throw error;this.rooms=data||[];
        const {data:invites}=await OnlineSystem.client.from('chat_room_invites').select('id,status,room:chat_rooms(id,name,visibility),sender:profiles!chat_room_invites_sender_id_fkey(display_name)').eq('receiver_id',OnlineSystem.user.id).eq('status','pending');
        const list=document.getElementById('chat-room-list');list.innerHTML=this.rooms.map(r=>{const active=this.current?.id===r.id;return `<article class="room-list-card ${active?'active':''}"><div><strong>${Game.escapeHTML(r.name)}</strong><small>${r.visibility}${r.language==='fr-FR'?' • Français':''}${r.owner?.display_name?` • by ${Game.escapeHTML(r.owner.display_name)}`:''} • limit ${r.member_limit}</small></div><button onclick="ChatRooms.join('${r.id}')" ${active?'disabled':''}>${active?'Current Room':'Join'}</button></article>`;}).join('')+(invites?.length?`<h4>Invitations</h4>${invites.map(i=>`<button class="room-list-button" onclick="ChatRooms.acceptInvite('${i.id}','${i.room.id}')">Accept ${Game.escapeHTML(i.room.name)} from ${Game.escapeHTML(i.sender?.display_name||'Hero')}</button>`).join('')}`:'');
    },
    async join(id){
        try{await this.ensureReady();const room=this.rooms.find(r=>r.id===id)||(await OnlineSystem.client.from('chat_rooms').select('*').eq('id',id).single()).data;if(!room)return;
            const {error}=await OnlineSystem.client.rpc('join_chat_room',{target_room:id});if(error)throw error;this.current=room;await this.loadMessages();await this.startRealtime();await this.heartbeat();this.startTimers();this.renderInfo();await this.refresh();
        }catch(e){Game.addNarrative(`Cannot enter room: ${e.message}`,'system');}
    },
    async loadMessages(){const {data,error}=await OnlineSystem.client.from('chat_room_messages').select('*,sender:profiles!chat_room_messages_sender_id_fkey(display_name)').eq('room_id',this.current.id).order('created_at',{ascending:true}).limit(100);if(error)throw error;this.messages=data||[];this.renderMessages();},
    renderMessages(){const log=document.getElementById('room-message-log');log.innerHTML=this.messages.length?this.messages.map(m=>`<p><strong>${Game.escapeHTML(m.sender?.display_name||'Hero')} says:</strong> ${Game.escapeHTML(m.body)} <small>${Game.escapeHTML(m.voice_id)}</small> <button onclick="OnlineSystem.speakText('${Game.escapeHTML(Game.escapeJS(`${m.sender?.display_name||'Hero'} says: ${m.body}`))}','${m.voice_id}','${this.current?.language||'en-US'}')">Listen</button></p>`).join(''):'<p>No messages in this room.</p>';log.scrollTop=log.scrollHeight;},
    async send(){if(!this.current)return;const input=document.getElementById('room-message-input'),body=input.value.trim();if(!body)return;if(Date.now()-OnlineSystem.lastMessageAt<2000){Game.addNarrative('Please wait two seconds between messages.','system');return;}const {error}=await OnlineSystem.client.from('chat_room_messages').insert({room_id:this.current.id,sender_id:OnlineSystem.user.id,body:body.slice(0,300),voice_id:OnlineSystem.selectedVoice});if(error){Game.addNarrative(error.message,'system');return;}OnlineSystem.lastMessageAt=Date.now();input.value='';},
    async startRealtime(){if(this.subscription)await OnlineSystem.client.removeChannel(this.subscription);this.subscription=OnlineSystem.client.channel(`room-${this.current.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_room_messages',filter:`room_id=eq.${this.current.id}`},async payload=>{const {data:sender}=await OnlineSystem.client.from('profiles').select('display_name').eq('id',payload.new.sender_id).single();const message={...payload.new,sender};this.messages.push(message);this.messages=this.messages.slice(-100);this.renderMessages();if(message.sender_id!==OnlineSystem.user.id&&localStorage.getItem('black_sword_auto_speak')!=='false')OnlineSystem.speakText(`${sender?.display_name||'Hero'} says: ${message.body}`,message.voice_id,this.current.language);}).subscribe();},
    async heartbeat(){if(!this.current)return;const {data,error}=await OnlineSystem.client.rpc('chat_room_heartbeat',{target_room:this.current.id});if(!error){this.current.occupancy=data.users;this.current.serverActivated=data.activated;this.current.activation_started_at=data.activation_started_at||this.current.activation_started_at;this.renderInfo();}},
    startTimers(){clearInterval(this.heartbeatTimer);clearInterval(this.countdownTimer);this.heartbeatTimer=setInterval(()=>this.heartbeat(),30000);this.countdownTimer=setInterval(()=>this.renderInfo(),1000);},
    renderInfo(){if(!this.current)return;const users=this.current.occupancy||0,owner=this.current.owner_id===OnlineSystem.user.id,elapsed=Date.now()-new Date(this.current.activation_started_at||this.current.created_at).getTime(),remaining=Math.max(0,this.current.activation_minutes*60000-elapsed),active=this.current.activated_at||this.current.serverActivated||this.current.activation_minutes===0;document.getElementById('active-room-info').textContent=`${this.current.name} • ${users} ${users===1?'user':'users'} • ${this.current.visibility}${active?' • permanently active':owner?` • activate in ${Math.ceil(remaining/60000)} minute(s) while you remain here`:' • awaiting owner activation'}`;['btn-room-invite','btn-room-blacklist','btn-delete-room'].forEach(id=>{const b=document.getElementById(id);if(b)b.disabled=!owner;});},
    async create(){try{await this.ensureReady();const name=document.getElementById('new-room-name').value.trim(),visibility=document.getElementById('new-room-visibility').value,limit=Number(document.getElementById('new-room-limit').value||20),wait=Number(document.getElementById('new-room-wait').value||5);if(name.length<2)throw new Error('Enter a room name.');const {data,error}=await OnlineSystem.client.rpc('create_custom_chat_room',{room_name:name,room_visibility:visibility,max_users:limit,wait_minutes:wait});if(error)throw error;await this.refresh();await this.join(data);Game.addNarrative(`${name} created. Remain in it for ${wait} minutes to activate it permanently.`,'treasure');}catch(e){Game.addNarrative(e.message,'system');}},
    async acceptInvite(inviteId,roomId){await OnlineSystem.client.from('chat_room_invites').update({status:'accepted'}).eq('id',inviteId).eq('receiver_id',OnlineSystem.user.id);await this.join(roomId);},
    async invite(){if(!this.current)return;try{const name=document.getElementById('room-player-name').value.trim(),target=await OnlineSystem.findProfile(name);if(!target)throw new Error('Hero name not found.');const {error}=await OnlineSystem.client.from('chat_room_invites').insert({room_id:this.current.id,sender_id:OnlineSystem.user.id,receiver_id:target.id});if(error)throw error;Game.addNarrative(`Invitation sent to ${target.display_name}.`,'npc');}catch(e){Game.addNarrative(e.message,'system');}},
    async blacklist(){if(!this.current)return;try{const name=document.getElementById('room-player-name').value.trim(),target=await OnlineSystem.findProfile(name);if(!target)throw new Error('Hero name not found.');const {error}=await OnlineSystem.client.rpc('blacklist_chat_user',{target_room:this.current.id,target_user:target.id,block_reason:'Blocked by room owner'});if(error)throw error;Game.addNarrative(`${target.display_name} was blacklisted and removed from the room.`,'system');}catch(e){Game.addNarrative(e.message,'system');}},
    async deleteCurrent(){if(!this.current||this.current.owner_id!==OnlineSystem.user.id){Game.addNarrative('Only the creator can delete this room.','system');return;}if(this.current.visibility==='personal'){Game.addNarrative('The permanent personal room cannot be deleted.','system');return;}if(!confirm(`Delete ${this.current.name}?`))return;const {error}=await OnlineSystem.client.from('chat_rooms').delete().eq('id',this.current.id).eq('owner_id',OnlineSystem.user.id);if(error){Game.addNarrative(error.message,'system');return;}this.current=null;document.getElementById('room-message-log').innerHTML='';await this.refresh();Game.addNarrative('Chat room deleted by its creator.','system');}
};
window.ChatRooms=ChatRooms;

document.getElementById('btn-refresh-rooms').addEventListener('click',()=>ChatRooms.refresh());
document.getElementById('btn-send-room-message').addEventListener('click',()=>ChatRooms.send());
document.getElementById('room-message-input').addEventListener('keypress',e=>{if(e.key==='Enter')ChatRooms.send();});
document.getElementById('btn-create-room').addEventListener('click',()=>ChatRooms.create());
document.getElementById('btn-room-invite').addEventListener('click',()=>ChatRooms.invite());
document.getElementById('btn-room-blacklist').addEventListener('click',()=>ChatRooms.blacklist());
document.getElementById('btn-delete-room').addEventListener('click',()=>ChatRooms.deleteCurrent());
const oldChatCommand=Game.processCommand.bind(Game);Game.processCommand=function(cmd){const c=cmd.toLowerCase().trim();if(c==='chat rooms'||c==='rooms'){ChatRooms.open();return;}if(c.startsWith('join room ')){ChatRooms.open().then(()=>{const q=c.slice(10),r=ChatRooms.rooms.find(x=>x.name.toLowerCase().includes(q));if(r)ChatRooms.join(r.id);});return;}oldChatCommand(cmd);};
