/** Secure default, personal, and owner-managed Supabase chat rooms. */
const ChatRooms={
    rooms:[],current:null,messages:[],subscription:null,heartbeatTimer:null,countdownTimer:null,messageExpiryTimer:null,openingPromise:null,joinPromise:null,joiningId:null,sending:false,expiryNoticeSpoken:false,
    isFresh(message,now=Date.now()){const expires=message?.expires_at?new Date(message.expires_at).getTime():new Date(message?.created_at||0).getTime()+300000;return Number.isFinite(expires)&&expires>now;},
    reconcileExpired(){this.messages=this.messages.filter(message=>this.isFresh(message));this.renderMessages();},
    scheduleExpiry(){clearTimeout(this.messageExpiryTimer);const next=Math.min(...this.messages.map(m=>new Date(m.expires_at||new Date(m.created_at).getTime()+300000).getTime()).filter(Number.isFinite));if(Number.isFinite(next))this.messageExpiryTimer=setTimeout(()=>this.reconcileExpired(),Math.max(0,next-Date.now()+30));},
    async ensureReady(){if(!OnlineSystem.ready)await OnlineSystem.init();if(!OnlineSystem.ready)throw new Error('Online account is still connecting.');},
    async open(){const panel=document.getElementById('chat-rooms-panel'),list=document.getElementById('chat-room-list');panel.classList.remove('hidden');if(!this.expiryNoticeSpoken){this.expiryNoticeSpoken=true;Game.addNarrative('Chat messages automatically expire after five minutes. Server moderation rejects abusive content, threats, spam, and links.','system');}if(this.openingPromise)return this.openingPromise;if(!list.children.length)list.innerHTML='<p>Loading chat rooms. The command input remains available.</p>';list.setAttribute('aria-busy','true');this.openingPromise=(async()=>{try{await this.ensureReady();const {error}=await OnlineSystem.client.rpc('ensure_personal_chat_room');if(error)throw error;await this.refresh();return true;}catch(e){console.warn('Private chat-room error:',e.message);list.innerHTML='<p>Chat rooms are temporarily unavailable. Try again when the connection is stable.</p>';Game.addNarrative('Chat rooms are temporarily unavailable. Please try again shortly.','system');return false;}finally{list.removeAttribute('aria-busy');this.openingPromise=null;}})();return this.openingPromise;},
    async refresh(){
        const {data,error}=await OnlineSystem.client.from('chat_rooms').select('*,owner:profiles!chat_rooms_owner_id_fkey(display_name)').order('created_at',{ascending:true});if(error)throw error;this.rooms=data||[];
        const {data:invites}=await OnlineSystem.client.from('chat_room_invites').select('id,status,room:chat_rooms(id,name,visibility),sender:profiles!chat_room_invites_sender_id_fkey(display_name)').eq('receiver_id',OnlineSystem.user.id).eq('status','pending');
        const list=document.getElementById('chat-room-list');list.innerHTML=this.rooms.map(r=>{const active=this.current?.id===r.id;return `<article class="room-list-card ${active?'active':''}"><div><strong>${Game.escapeHTML(r.name)}</strong><small>${r.visibility}${r.language==='fr-FR'?' • Français':''}${r.owner?.display_name?` • by ${Game.escapeHTML(r.owner.display_name)}`:''} • limit ${r.member_limit}</small></div><button onclick="ChatRooms.join('${r.id}')" ${active?'disabled':''}>${active?'Current Room':'Join'}</button></article>`;}).join('')+(invites?.length?`<h4>Invitations</h4>${invites.map(i=>`<button class="room-list-button" onclick="ChatRooms.acceptInvite('${i.id}','${i.room.id}')">Accept ${Game.escapeHTML(i.room.name)} from ${Game.escapeHTML(i.sender?.display_name||'Hero')}</button>`).join('')}`:'');
    },
    async join(id){if(this.joinPromise){if(this.joiningId===id)return this.joinPromise;Game.addNarrative('Another chat room is still loading. Please wait.','system');return false;}this.joiningId=id;const log=document.getElementById('room-message-log');log.setAttribute('aria-busy','true');this.joinPromise=(async()=>{try{await this.ensureReady();const room=this.rooms.find(r=>r.id===id)||(await OnlineSystem.client.from('chat_rooms').select('*').eq('id',id).single()).data;if(!room)return false;const {error}=await OnlineSystem.client.rpc('join_chat_room',{target_room:id});if(error)throw error;this.current=room;await this.loadMessages();await this.startRealtime();await this.heartbeat();this.startTimers();this.renderInfo();await this.refresh();document.getElementById('room-message-input')?.focus();return true;}catch(e){Game.addNarrative(`Cannot enter room: ${e.message}`,'system');return false;}finally{log.removeAttribute('aria-busy');this.joinPromise=null;this.joiningId=null;}})();return this.joinPromise;},
    async loadMessages(){const now=new Date().toISOString();const {data,error}=await OnlineSystem.client.from('chat_room_messages').select('*,sender:profiles!chat_room_messages_sender_id_fkey(display_name)').eq('room_id',this.current.id).gt('expires_at',now).order('created_at',{ascending:false}).limit(50);if(error)throw error;this.messages=(data||[]).filter(m=>this.isFresh(m)).reverse().map(m=>OnlineSystem.normalizeLanguageMessage(m));this.renderMessages();},
    createMessageNode(message){const row=document.createElement('p');row.dataset.messageId=String(message.id);const span=document.createElement('span');span.id=`room-msg-${message.id}`;const strong=document.createElement('strong');strong.textContent=`${message.sender?.display_name||'Hero'} says:`;span.append(strong,document.createTextNode(` ${message.body}`));const button=document.createElement('button');button.textContent='Listen';button.setAttribute('aria-label',`Listen to message from ${message.sender?.display_name||'Hero'}`);button.addEventListener('click',()=>this.speakMessage(message.id));row.append(span,document.createTextNode(' '),button);return row;},
    renderMessages(){const log=document.getElementById('room-message-log');if(!log)return;this.messages=this.messages.filter(m=>this.isFresh(m)).slice(-50);log.setAttribute('aria-live','off');log.setAttribute('aria-busy','true');const fragment=document.createDocumentFragment();if(this.messages.length)this.messages.forEach(message=>fragment.append(this.createMessageNode(message)));else{const empty=document.createElement('p');empty.dataset.empty='true';empty.textContent='No unexpired messages in this room.';fragment.append(empty);}log.replaceChildren(fragment);log.scrollTop=log.scrollHeight;window.TranslationService?.translateRoomLog?.(this.messages);this.scheduleExpiry();setTimeout(()=>{if(log.isConnected){log.setAttribute('aria-live','polite');log.removeAttribute('aria-busy');}},0);},
    appendMessage(message){const log=document.getElementById('room-message-log');if(!log)return;document.getElementById(`room-msg-${message.id}`)?.closest('p')?.remove();log.querySelector('[data-empty="true"]')?.remove();const nearBottom=log.scrollHeight-log.scrollTop-log.clientHeight<80;log.append(this.createMessageNode(message));while(log.children.length>50)log.firstElementChild?.remove();if(nearBottom)log.scrollTop=log.scrollHeight;window.TranslationService?.translateRoomLog?.([message]);this.scheduleExpiry();},
    removeMessage(id){document.getElementById(`room-msg-${id}`)?.closest('p')?.remove();const log=document.getElementById('room-message-log');if(log&&!log.children.length){const empty=document.createElement('p');empty.dataset.empty='true';empty.textContent='No unexpired messages in this room.';log.append(empty);}},
    async speakMessage(id){const m=this.messages.find(x=>String(x.id)===String(id));if(!m)return;const text=await (window.TranslationService?.translate?.(m.body,m.source_language||'en')||Promise.resolve(m.body));OnlineSystem.speakText(`${m.sender?.display_name||'Hero'} says: ${text}`,m.voice_id,window.TranslationService?.target||this.current?.language||'en');},
    async send(){if(!this.current||this.sending)return false;const input=document.getElementById('room-message-input'),button=document.getElementById('btn-send-room-message'),body=input.value.trim();if(!body)return false;const moderation=OnlineSystem.checkChatContent(body);if(moderation){Game.addNarrative(moderation,'system');return false;}if(Date.now()-OnlineSystem.lastMessageAt<2000){Game.addNarrative('Please wait two seconds between messages.','system');return false;}this.sending=true;button.disabled=true;button.setAttribute('aria-busy','true');try{let {error}=await OnlineSystem.client.from('chat_room_messages').insert({room_id:this.current.id,sender_id:OnlineSystem.user.id,body:body.slice(0,300),voice_id:OnlineSystem.selectedVoice,source_language:window.TranslationService?.sourceLanguage?.()||'en'});if(error&&/source_language|schema cache/i.test(error.message||''))({error}=await OnlineSystem.client.from('chat_room_messages').insert({room_id:this.current.id,sender_id:OnlineSystem.user.id,body:`[[lang:${window.TranslationService?.sourceLanguage?.()||'en'}]]${body.slice(0,270)}`,voice_id:OnlineSystem.selectedVoice}));if(error){Game.addNarrative(error.message,'system');return false;}OnlineSystem.lastMessageAt=Date.now();input.value='';return true;}finally{this.sending=false;button.disabled=false;button.removeAttribute('aria-busy');input.focus();}},
    async startRealtime(){if(this.subscription)await OnlineSystem.client.removeChannel(this.subscription);const roomId=this.current.id;this.subscription=OnlineSystem.client.channel(`room-${roomId}`).on('postgres_changes',{event:'*',schema:'public',table:'chat_room_messages',filter:`room_id=eq.${roomId}`},async payload=>{if(this.current?.id!==roomId)return;if(payload.eventType==='DELETE'){this.messages=this.messages.filter(m=>String(m.id)!==String(payload.old?.id));this.removeMessage(payload.old?.id);this.scheduleExpiry();return;}if(payload.eventType!=='INSERT'||payload.new.room_id!==roomId||!this.isFresh(payload.new))return;const {data:sender}=await OnlineSystem.client.from('profiles').select('display_name').eq('id',payload.new.sender_id).single();const message=OnlineSystem.normalizeLanguageMessage({...payload.new,sender});if(!this.isFresh(message)||this.current?.id!==roomId)return;this.messages=this.messages.filter(m=>String(m.id)!==String(message.id));this.messages.push(message);this.messages=this.messages.slice(-50);this.appendMessage(message);if(message.sender_id!==OnlineSystem.user.id&&localStorage.getItem('black_sword_auto_speak')==='true'){const translated=await(window.TranslationService?.translate?.(message.body,message.source_language||'en')||Promise.resolve(message.body));if(this.isFresh(message)&&this.current?.id===roomId)OnlineSystem.speakText(`${sender?.display_name||'Hero'} says: ${translated}`,message.voice_id,window.TranslationService?.target||this.current.language);}}).subscribe();},
    async heartbeat(){if(!this.current)return;const {data,error}=await OnlineSystem.client.rpc('chat_room_heartbeat',{target_room:this.current.id});if(!error){this.current.occupancy=data.users;this.current.serverActivated=data.activated;this.current.activation_started_at=data.activation_started_at||this.current.activation_started_at;this.renderInfo();}},
    startTimers(){clearInterval(this.heartbeatTimer);clearInterval(this.countdownTimer);this.heartbeatTimer=setInterval(()=>{if(!document.hidden)this.heartbeat();},30000);this.countdownTimer=setInterval(()=>{if(!document.hidden)this.renderInfo();},10000);},
    renderInfo(){if(!this.current)return;const users=this.current.occupancy||0,owner=this.current.owner_id===OnlineSystem.user.id,elapsed=Date.now()-new Date(this.current.activation_started_at||this.current.created_at).getTime(),remaining=Math.max(0,this.current.activation_minutes*60000-elapsed),active=this.current.activated_at||this.current.serverActivated||this.current.activation_minutes===0,info=document.getElementById('active-room-info'),text=`${this.current.name} • ${users} ${users===1?'user':'users'} • ${this.current.visibility}${active?' • permanently active':owner?` • activate in ${Math.ceil(remaining/60000)} minute(s) while you remain here`:' • awaiting owner activation'}`;if(info.textContent!==text)info.textContent=text;['btn-room-invite','btn-room-blacklist','btn-delete-room'].forEach(id=>{const b=document.getElementById(id);if(b&&b.disabled===owner)b.disabled=!owner;});},
    async create(){try{await this.ensureReady();const name=document.getElementById('new-room-name').value.trim(),visibility=document.getElementById('new-room-visibility').value,limit=Number(document.getElementById('new-room-limit').value||20),wait=Number(document.getElementById('new-room-wait').value||5);if(name.length<2)throw new Error('Enter a room name.');const {data,error}=await OnlineSystem.client.rpc('create_custom_chat_room',{room_name:name,room_visibility:visibility,max_users:limit,wait_minutes:wait});if(error)throw error;await this.refresh();await this.join(data);Game.addNarrative(`${name} created. Remain in it for ${wait} minutes to activate it permanently.`,'treasure');}catch(e){Game.addNarrative(e.message,'system');}},
    async acceptInvite(inviteId,roomId){await OnlineSystem.client.from('chat_room_invites').update({status:'accepted'}).eq('id',inviteId).eq('receiver_id',OnlineSystem.user.id);await this.join(roomId);},
    async invite(){if(!this.current)return;try{const name=document.getElementById('room-player-name').value.trim(),target=await OnlineSystem.findProfile(name);if(!target)throw new Error('Hero name not found.');const {error}=await OnlineSystem.client.from('chat_room_invites').insert({room_id:this.current.id,sender_id:OnlineSystem.user.id,receiver_id:target.id});if(error)throw error;Game.addNarrative(`Invitation sent to ${target.display_name}.`,'npc');}catch(e){Game.addNarrative(e.message,'system');}},
    async blacklist(){if(!this.current)return;try{const name=document.getElementById('room-player-name').value.trim(),target=await OnlineSystem.findProfile(name);if(!target)throw new Error('Hero name not found.');const {error}=await OnlineSystem.client.rpc('blacklist_chat_user',{target_room:this.current.id,target_user:target.id,block_reason:'Blocked by room owner'});if(error)throw error;Game.addNarrative(`${target.display_name} was blacklisted and removed from the room.`,'system');}catch(e){Game.addNarrative(e.message,'system');}},
    async deleteCurrent(){if(!this.current||this.current.owner_id!==OnlineSystem.user.id){Game.addNarrative('Only the creator can delete this room.','system');return;}if(this.current.visibility==='personal'){Game.addNarrative('The permanent personal room cannot be deleted.','system');return;}if(!confirm(`Delete ${this.current.name}?`))return;const {error}=await OnlineSystem.client.from('chat_rooms').delete().eq('id',this.current.id).eq('owner_id',OnlineSystem.user.id);if(error){Game.addNarrative(error.message,'system');return;}this.current=null;document.getElementById('room-message-log').innerHTML='';await this.refresh();Game.addNarrative('Chat room deleted by its creator.','system');}
};
window.ChatRooms=ChatRooms;

document.getElementById('btn-refresh-rooms').addEventListener('click',()=>ChatRooms.refresh());
document.getElementById('btn-send-room-message').addEventListener('click',()=>ChatRooms.send());
document.getElementById('room-message-input').addEventListener('keypress',e=>{if(e.key==='Enter')ChatRooms.send();});
document.getElementById('btn-create-room').addEventListener('click',()=>ChatRooms.create());
document.getElementById('btn-room-invite').addEventListener('click',()=>ChatRooms.invite());
document.getElementById('btn-room-blacklist').addEventListener('click',()=>ChatRooms.blacklist());
document.getElementById('btn-delete-room').addEventListener('click',()=>ChatRooms.deleteCurrent());
const oldChatCommand=Game.processCommand.bind(Game);Game.processCommand=function(cmd){const c=cmd.toLowerCase().trim();if(c==='chat rooms'||c==='rooms'){ChatRooms.open();return;}if(c.startsWith('join room ')){ChatRooms.open().then(()=>{const q=c.slice(10),r=ChatRooms.rooms.find(x=>x.name.toLowerCase().includes(q));if(r)ChatRooms.join(r.id);});return;}oldChatCommand(cmd);};
