/** Original equipment sets and quantity-based shop interface. */
(() => {
    const gear = {
        'iron helm':{name:'Iron Helm',type:'helmet',set:'Iron Guard',defense:55,str:60,dex:50,int:50,wis:50,hp:80,mp:50,value:180,desc:'A closed iron helm from the Iron Guard set.'},
        'iron gauntlets':{name:'Iron Gauntlets',type:'gloves',set:'Iron Guard',defense:50,str:75,dex:50,int:50,wis:50,hp:60,mp:50,value:170,desc:'Heavy gauntlets that strengthen blunt and sharp attacks.'},
        'iron boots':{name:'Iron Boots',type:'boots',set:'Iron Guard',defense:60,str:60,dex:50,int:50,wis:50,hp:75,mp:50,value:165,desc:'Armored boots built for holding a battle line.'},
        'runed staff':{name:'Runed Staff',type:'weapon',weaponType:'blunt',set:'Arcane Weaver',damage:150,str:50,dex:60,int:180,wis:140,hp:80,mp:220,value:420,desc:'A staff carved with six responsive spell runes.'},
        'arcane hood':{name:'Arcane Hood',type:'helmet',set:'Arcane Weaver',defense:50,str:50,dex:60,int:140,wis:110,hp:60,mp:170,value:280,desc:'A hood that sharpens magical concentration.'},
        'spell gloves':{name:'Spell Gloves',type:'gloves',set:'Arcane Weaver',defense:50,str:50,dex:70,int:160,wis:100,hp:50,mp:150,value:300,desc:'Fine gloves that stabilize difficult incantations.'},
        'mana boots':{name:'Mana Boots',type:'boots',set:'Arcane Weaver',defense:50,str:50,dex:80,int:120,wis:100,hp:70,mp:140,value:260,desc:'Quiet boots leaving a faint trail of blue sparks.'},
        'mana ring':{name:'Mana Ring',type:'accessory',set:'Arcane Weaver',str:50,dex:50,int:130,wis:120,hp:50,mp:180,value:350,desc:'A ring storing reserve magic points.'},
        'twin shadow daggers':{name:'Twin Shadow Daggers',type:'weapon',weaponType:'sharp',set:'Shadow Hunter',damage:175,str:90,dex:220,int:70,wis:60,hp:80,mp:90,value:460,desc:'Paired sharp blades balanced for rapid multiple strikes.'},
        'shadow hood':{name:'Shadow Hood',type:'helmet',set:'Shadow Hunter',defense:50,str:60,dex:150,int:70,wis:60,hp:70,mp:70,value:250,desc:'A dark hood that softens movement and outline.'},
        'shadow gloves':{name:'Shadow Gloves',type:'gloves',set:'Shadow Hunter',defense:50,str:70,dex:170,int:60,wis:50,hp:60,mp:60,value:270,desc:'Grip-enhancing gloves for bows and daggers.'},
        'shadow boots':{name:'Shadow Boots',type:'boots',set:'Shadow Hunter',defense:50,str:60,dex:180,int:50,wis:60,hp:75,mp:60,value:275,desc:'Soft boots for silent tracking.'},
        'blessed plate':{name:'Blessed Plate',type:'armor',set:'Auralis Champion',defense:180,str:160,dex:60,int:100,wis:170,hp:240,mp:140,value:650,desc:'Plate armor carrying the mark of Auralis.'},
        'sun helm':{name:'Sun Helm',type:'helmet',set:'Auralis Champion',defense:120,str:110,dex:60,int:100,wis:160,hp:180,mp:120,value:440,desc:'A gold-edged helm glowing softly near undead creatures.'},
        'prayer gauntlets':{name:'Prayer Gauntlets',type:'gloves',set:'Auralis Champion',defense:100,str:130,dex:60,int:110,wis:180,hp:150,mp:150,value:430,desc:'Holy gauntlets used for healing and hammer strikes.'},
        'pilgrim boots':{name:'Pilgrim Boots',type:'boots',set:'Auralis Champion',defense:90,str:80,dex:90,int:90,wis:150,hp:140,mp:130,value:360,desc:'Blessed boots made for long journeys to the temple.'}
    };
    Object.assign(WorldData.items,gear);
    Object.assign(WorldData.items['iron sword'],{set:'Iron Guard'});
    Object.assign(WorldData.items['chainmail'],{set:'Iron Guard'});
    Object.assign(WorldData.items['mage robe'],{set:'Arcane Weaver'});
    Object.assign(WorldData.items['leather armor'],{set:'Shadow Hunter'});
    Object.assign(WorldData.items["saint's maul"],{set:'Auralis Champion'});
    Object.assign(WorldData.items['blessed amulet'],{set:'Auralis Champion'});
    WorldData.locations.arcane_enchantery.shop='relics';

    const addStock=(kind,id,price)=>{const stock=ExpansionData.shopStock[kind];if(!stock.some(x=>x.id===id))stock.push({id,price});};
    ['iron helm','iron gauntlets','iron boots','blessed plate','sun helm','prayer gauntlets','pilgrim boots'].forEach(id=>addStock('weapons',id,WorldData.items[id].value));
    ['runed staff','arcane hood','spell gloves','mana boots','mana ring','twin shadow daggers','shadow hood','shadow gloves','shadow boots'].forEach(id=>addStock('relics',id,WorldData.items[id].value));

    Game.listShopItems=function(){const loc=WorldData.locations[this.state.location],stock=ExpansionData.shopStock[loc?.shop]||[];if(!loc?.shop){this.addNarrative('There is no shop at this location.','system');return;}this.addNarrative(`${loc.name} lists ${stock.length} item types: ${stock.map((s,i)=>`${i+1}. ${WorldData.items[s.id]?.name||s.id} (${s.price} rupees)`).join('; ')}.`,'item');};
    Game.inspectShopItem=function(id){const item=WorldData.items[id];if(!item)return;const stats=['damage','defense','str','dex','int','wis','hp','mp'].filter(k=>item[k]!=null).map(k=>`${k.toUpperCase()} ${item[k]}`).join(', ');this.addNarrative(`${item.name}: ${item.desc||''} ${stats}. ${item.set?`Set: ${item.set}.`:''}`,'item');};
    Game.compareShopItem=function(id){const item=WorldData.items[id],p=this.state.player;if(!item)return;const slot=item.type==='weapon'?'weapon':item.type==='armor'?'armor':item.type;const current=p[slot]||'none';const currentItem=Object.values(WorldData.items).find(i=>i.name===current);this.addNarrative(`${item.name} compared with ${current}: damage ${item.damage||0} vs ${currentItem?.damage||0}; defense ${item.defense||0} vs ${currentItem?.defense||0}; HP +${item.hp||0}; MP +${item.mp||0}.`,'system');};
    Game.buyShopQuantity=function(id){const loc=WorldData.locations[this.state.location],entry=(ExpansionData.shopStock[loc?.shop]||[]).find(s=>s.id===id),select=document.getElementById(`shop-qty-${id.replace(/[^a-z0-9]/gi,'-')}`),quantity=Math.max(1,Math.min(10,Number(select?.value||1)));if(!entry)return;const cost=entry.price*quantity;if(this.state.player.gold<cost){this.addNarrative(`Not enough rupees. ${quantity} cost ${cost}.`,'system');return;}this.state.player.gold-=cost;for(let i=0;i<quantity;i++)this.addItemToInventory(id,WorldData.items[id]);this.addNarrative(`Bought ${quantity} ${WorldData.items[id].name} for ${cost} rupees.`,'item');this.updateHUD();this.save();this.showShop();};
    Game.showShop=function(){const panel=document.getElementById('shop-panel'),content=document.getElementById('shop-content'),loc=WorldData.locations[this.state.location];if(!loc?.shop){content.innerHTML='<p>There is no shop at this physical location. Walk to a marketplace, weapon shop, provision shop, alchemist, or enchantery.</p>';panel.classList.remove('hidden');return;}const stock=ExpansionData.shopStock[loc.shop]||[];content.innerHTML=`<div class="shop-summary"><strong>${this.escapeHTML(loc.name)} — ${this.escapeHTML(loc.shop)} shop</strong><span>${stock.length} item types • ${this.state.player.gold} rupees</span><button onclick="Game.listShopItems()">List ${stock.length} Items</button></div>`+stock.map(s=>{const item=WorldData.items[s.id],owned=this.state.inventory.find(i=>i.id===s.id)?.quantity||0,safe=s.id.replace(/[^a-z0-9]/gi,'-');return `<article class="shop-item-card"><div><strong>${this.escapeHTML(item?.name||s.id)}</strong><small>${this.escapeHTML(item?.type||'item')} • ${s.price} rupees • owned ${owned}${item?.set?` • ${this.escapeHTML(item.set)} set`:''}</small><p>${this.escapeHTML(item?.desc||'')}</p></div><label>Quantity <select id="shop-qty-${safe}">${Array.from({length:10},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label><div class="shop-actions"><button onclick="Game.buyShopQuantity('${this.escapeHTML(this.escapeJS(s.id))}')">Buy</button><button onclick="Game.inspectShopItem('${this.escapeHTML(this.escapeJS(s.id))}')">Examine</button><button onclick="Game.compareShopItem('${this.escapeHTML(this.escapeJS(s.id))}')">Compare</button></div></article>`}).join('');panel.classList.remove('hidden');};

    const customSlots=['helmet','gloves','boots'];
    const oldEquip=Game.equipItem.bind(Game);
    Game.equipItem=function(name){const item=this.state.inventory.find(i=>i.name.toLowerCase().includes(name.toLowerCase()));if(!item||!customSlots.includes(item.type)){oldEquip(name);this.recalculateSetBonuses();return;}const p=this.state.player,slot=item.type;p.slotItemBonuses||={};const old=p.slotItemBonuses[slot];if(old){['str','dex','int','wis'].forEach(k=>p[k]-=old[k]||0);p.maxHp-=old.hp||0;p.maxMp-=old.mp||0;}const bonus={str:item.str||0,dex:item.dex||0,int:item.int||0,wis:item.wis||0,hp:item.hp||0,mp:item.mp||0};p[slot]=item.name;p.slotItemBonuses[slot]=bonus;['str','dex','int','wis'].forEach(k=>p[k]+=bonus[k]);p.maxHp+=bonus.hp;p.maxMp+=bonus.mp;p.hp=Math.min(p.maxHp,p.hp+bonus.hp);p.mp=Math.min(p.maxMp,p.mp+bonus.mp);this.addNarrative(`Equipped ${item.name} in the ${slot} slot.`,'treasure');this.recalculateSetBonuses();this.updateHUD();this.save();};
    Game.recalculateSetBonuses=function(){const p=this.state.player;p.activeSetBonus||={str:0,dex:0,int:0,wis:0,hp:0,mp:0};const old=p.activeSetBonus;['str','dex','int','wis'].forEach(k=>p[k]-=old[k]||0);p.maxHp-=old.hp||0;p.maxMp-=old.mp||0;const names=[p.weapon,p.armor,p.helmet,p.gloves,p.boots,p.accessory].filter(Boolean),counts={};names.forEach(n=>{const item=Object.values(WorldData.items).find(i=>i.name===n);if(item?.set)counts[item.set]=(counts[item.set]||0)+1;});const total={str:0,dex:0,int:0,wis:0,hp:0,mp:0};Object.entries(counts).forEach(([set,count])=>{if(count>=2){total.str+=20;total.dex+=20;total.int+=20;total.wis+=20;}if(count>=4){total.hp+=100;total.mp+=100;}if(count>=6){total.str+=50;total.dex+=50;total.int+=50;total.wis+=50;total.hp+=150;total.mp+=150;}});['str','dex','int','wis'].forEach(k=>p[k]+=total[k]);p.maxHp+=total.hp;p.maxMp+=total.mp;p.activeSetBonus=total;p.activeSets=Object.entries(counts).filter(([,n])=>n>=2).map(([set,n])=>`${set} ${n}/6`);};
    Object.values(WorldData.locations).flatMap(loc=>loc.items||[]).forEach(id=>{if(!WorldData.items[id])WorldData.items[id]={name:id.replace(/\b\w/g,c=>c.toUpperCase()),type:'misc',value:10,desc:`${id} is a discoverable object from this region of Kandor.`};});
    Object.entries(WorldData.items).forEach(([id,item])=>{item.name||=(id[0].toUpperCase()+id.slice(1));item.desc||=`${item.name} is a ${item.type||'general'} item found in Kandor.`;item.ability||=(item.type==='weapon'?`Deals ${item.damage||0} weapon damage.`:item.type==='armor'||['helmet','gloves','boots'].includes(item.type)?`Provides ${item.defense||0} defense and equipment bonuses.`:item.effect==='heal'?`Restores ${item.value||0} HP.`:item.effect==='mana'?`Restores ${item.value||0} MP.`:item.effect==='both'?`Restores ${item.value||0} HP and MP.`:item.type==='quest'?'Used for a quest or puzzle.':'Can be carried, stored, sold, or examined.');});
    Game.itemDetail=function(item){const stats=['damage','defense','str','dex','int','wis','hp','mp'].filter(k=>item[k]!=null).map(k=>`${k.toUpperCase()} ${item[k]}`).join(', '),ench=Object.entries(item.enchantments||{}).map(([k,v])=>`${k} rank ${v}`).join(', ');return `${item.name}. ${item.desc} Ability: ${item.ability} Type: ${item.type||'item'}${item.weaponType?`, ${item.weaponType}`:''}. ${stats||'No combat attributes'}. Value: ${item.value||Math.max(1,Math.floor((item.damage||item.defense||10)*.35))} rupees.${item.set?` Set: ${item.set}.`:''}${ench?` Enchantments: ${ench}.`:''}`;};
    const oldExamine=Game.examineEntity?.bind(Game);Game.examineEntity=function(query){const q=query.toLowerCase(),item=this.state.inventory.find(i=>i.name.toLowerCase().includes(q))||Object.values(WorldData.items).find(i=>i.name.toLowerCase().includes(q));if(item){this.addNarrative(this.itemDetail(item),'item');return;}if(q==='weapon'&&this.state.player.weapon){const w=Object.values(WorldData.items).find(i=>i.name===this.state.player.weapon);if(w){this.addNarrative(this.itemDetail(w),'item');return;}}if(oldExamine)oldExamine(query);};
    const oldCommand=Game.processCommand.bind(Game);Game.processCommand=function(cmd){const c=cmd.toLowerCase().trim();if(c==='list shop'||c==='list items'){this.listShopItems();return;}if(c.startsWith('compare ')){const q=c.slice(8),item=Object.entries(WorldData.items).find(([,i])=>i.name.toLowerCase().includes(q));if(item)this.compareShopItem(item[0]);else this.addNarrative('No matching equipment to compare.','system');return;}oldCommand(cmd);};
})();
