import { Chess } from './assets/vendor/chess.js';

const RULES={
 ludo:'Two players race four tokens. Roll six to leave the yard. Move exactly by the die. Landing on an opponent captures it unless the square is safe. Bring all four tokens home.',
 snakes:'Roll one die and reach square 100 exactly. Ladders move upward and snakes move downward. First to 100 wins.',
 chess:'Standard legal chess rules are enforced by chess.js, including check, checkmate, castling, promotion and en passant. Enter moves such as e2e4.',
 carrom:'Accessible turn simulation: choose angle 0–359 and power 1–10. Pocket your nine coins and then the queen. Fouls pass the turn.',
 blackjack:'Reach 21 without exceeding it. Number cards use face value, face cards count 10, and Ace counts 1 or 11. Dealer draws to 17.'
};
const SNAKES={17:7,54:34,62:19,64:60,87:24,93:73,95:75,99:78},LADDERS={4:14,9:31,20:38,28:84,40:59,51:67,63:81,71:91};
const esc=s=>Game.escapeHTML(String(s));

const GameHall={type:null,state:null,chess:null,onlineSession:null,version:0,subscription:null,
 initWorld(){for(const city of CityDirectory.cities){const lobby=`${city.key}_game_hall`,park=city.targets.park;WorldData.locations[lobby]={name:`${city.label} — Accessible Game Hall`,region:city.label,description:'A physical indoor game hall with five screen-reader-friendly rooms, rule desks, dice tables, card tables and quiet strategy boards.',exits:{down:park,north:`${lobby}_ludo`,east:`${lobby}_snakes`,south:`${lobby}_chess`,west:`${lobby}_carrom`,up:`${lobby}_blackjack`},features:['accessible game hall','rule desk','board game rooms'],items:[],enemies:[],safe:true,music:'inn'};WorldData.locations[park].exits.up=lobby;city.targets.game_hall=lobby;for(const [dir,type] of [['north','ludo'],['east','snakes'],['south','chess'],['west','carrom'],['up','blackjack']])WorldData.locations[`${lobby}_${type}`]={name:`${city.label} Game Hall — ${type[0].toUpperCase()+type.slice(1)} Room`,region:`${city.label} Game Hall`,description:`An accessible ${type} room with spoken rules, large controls, clear turn feedback and realistic board sounds.`,exits:{down:lobby},features:['game hall room',type],items:[],enemies:[],safe:true,music:'inn'};}
 },
 inject(){const panel=document.createElement('div');panel.id='game-hall-panel';panel.className='panel hidden wide-panel';panel.innerHTML=`<h3>Accessible Game Hall</h3><div id="hall-game-list" class="directory-grid"></div><div id="hall-help" class="settings-note"></div><div id="hall-status" aria-live="polite"></div><div id="hall-board" class="hall-board" aria-live="polite"></div><div id="hall-controls" class="hall-controls"></div><details><summary>Online friend match</summary><input id="hall-session-name" placeholder="Match name"><input id="hall-invite-name" placeholder="Friend's exact hero name"><button id="hall-create-online">Create Online Match</button><button id="hall-invite">Invite Friend</button></details><p><a href="https://play.google.com/store/apps/details?id=com.labs.ludo" target="_blank" rel="noopener">KM Sanjay accessible dice-games listing</a> • <a href="https://en.wikipedia.org/wiki/Ludo" target="_blank" rel="noopener">Public Ludo rules</a> • <a href="https://en.wikipedia.org/wiki/Chess" target="_blank" rel="noopener">Public Chess rules</a></p><button class="menu-btn close-btn" onclick="document.getElementById('game-hall-panel').classList.add('hidden')">Close</button>`;document.getElementById('game-screen').appendChild(panel);document.querySelector('.action-btns').insertAdjacentHTML('beforeend','<button class="action-btn" id="btn-game-hall">Game Hall</button>');document.getElementById('btn-game-hall').addEventListener('click',()=>this.enterOrOpen());document.getElementById('hall-create-online').addEventListener('click',()=>this.createOnline());document.getElementById('hall-invite').addEventListener('click',()=>this.invite());},
 enterOrOpen(){const city=Game.currentCityDefinition?.(),target=city?.targets?.game_hall;if(!target){Game.addNarrative('Enter a city to find its Game Hall.','system');return;}if(!Game.state.location.startsWith(target)){Game.routeToCityLandmark('game_hall');return;}this.open();},
 open(){this.loadInvites();const room=WorldData.locations[Game.state.location]?.features?.find(x=>['ludo','snakes','chess','carrom','blackjack'].includes(x));document.getElementById('game-hall-panel').classList.remove('hidden');document.getElementById('hall-game-list').innerHTML=['ludo','snakes','chess','carrom','blackjack'].map(t=>`<button onclick="GameHall.select('${t}')">${t==='snakes'?'Snakes & Ladders':t[0].toUpperCase()+t.slice(1)}</button>`).join('');if(room)this.select(room);},
 select(type){this.type=type;document.getElementById('hall-help').textContent=RULES[type];document.getElementById('hall-status').textContent='Read the rules, then start a local game against the computer.';document.getElementById('hall-controls').innerHTML=`<button onclick="GameHall.startLocal()">Start vs Computer</button>`;document.getElementById('hall-board').innerHTML='';},
 startLocal(){if(this.type==='ludo')this.state={tokens:[[-1,-1,-1,-1],[-1,-1,-1,-1]],turn:0,roll:null,winner:null};if(this.type==='snakes')this.state={positions:[0,0],turn:0,winner:null};if(this.type==='chess'){this.chess=new Chess();this.state={fen:this.chess.fen(),winner:null};}if(this.type==='carrom')this.state={scores:[0,0],queen:false,turn:0,winner:null};if(this.type==='blackjack')this.startBlackjack();MusicSystem.playSFX(this.type==='blackjack'?'card-shuffle':'board-turn');this.render();},
 roll(){if(!this.state||!['ludo','snakes'].includes(this.type))return;const die=1+Math.floor(Math.random()*6);MusicSystem.playSFX('board-dice');if(this.type==='snakes')this.snakesMove(die);else{this.state.roll=die;this.render();if(this.state.turn===1)this.botLudo();}},
 snakesMove(die){const p=this.state.turn;let next=this.state.positions[p]+die;if(next<=100)this.state.positions[p]=next;if(LADDERS[this.state.positions[p]])this.state.positions[p]=LADDERS[this.state.positions[p]];else if(SNAKES[this.state.positions[p]])this.state.positions[p]=SNAKES[this.state.positions[p]];document.getElementById('hall-status').textContent=`${p?'Computer':'You'} rolled ${die} and reached ${this.state.positions[p]}.`;MusicSystem.playSFX('board-piece');if(this.state.positions[p]===100){this.state.winner=p;this.finish(`${p?'Computer':'You'} won Snakes & Ladders.`);return;}this.state.turn=1-p;this.render();if(this.state.turn===1)setTimeout(()=>this.roll(),500);},
 moveLudo(token){const p=this.state.turn,die=this.state.roll,pos=this.state.tokens[p][token];if(die==null)return;let next=pos;if(pos<0&&die===6)next=0;else if(pos>=0&&pos+die<=56)next=pos+die;else{document.getElementById('hall-status').textContent='That token cannot use this roll.';MusicSystem.playSFX('board-error');return;}this.state.tokens[p][token]=next;const safe=[0,8,13,21,26,34,39,47];if(!safe.includes(next)&&next<52)this.state.tokens[1-p]=this.state.tokens[1-p].map(x=>x===next?-1:x);MusicSystem.playSFX('board-piece');this.state.roll=null;if(this.state.tokens[p].every(x=>x===56)){this.finish(`${p?'Computer':'You'} won Ludo.`);return;}this.state.turn=1-p;this.render();if(this.state.turn===1)setTimeout(()=>this.roll(),500);},
 botLudo(){if(this.state.turn!==1)return;const legal=this.state.tokens[1].map((p,i)=>({p,i})).filter(x=>(x.p<0&&this.state.roll===6)||(x.p>=0&&x.p+this.state.roll<=56));if(legal.length)this.moveLudo(legal[0].i);else{this.state.roll=null;this.state.turn=0;this.render();}},
 startBlackjack(){const deck=[];for(const suit of ['S','H','D','C'])for(const rank of ['A','2','3','4','5','6','7','8','9','10','J','Q','K'])deck.push(rank+suit);for(let i=deck.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}this.state={deck,player:[deck.pop(),deck.pop()],dealer:[deck.pop(),deck.pop()],done:false};},
 handValue(hand){let value=0,aces=0;for(const c of hand){const r=c.slice(0,-1);if(r==='A'){aces++;value+=11}else value+=['K','Q','J'].includes(r)?10:Number(r);}while(value>21&&aces){value-=10;aces--;}return value;},
 hit(){if(this.type!=='blackjack'||this.state.done)return;this.state.player.push(this.state.deck.pop());MusicSystem.playSFX('card-draw');if(this.handValue(this.state.player)>21)this.finish('You bust. Dealer wins.');else this.render();},
 stand(){while(this.handValue(this.state.dealer)<17)this.state.dealer.push(this.state.deck.pop());const p=this.handValue(this.state.player),d=this.handValue(this.state.dealer);this.finish(d>21||p>d?'You win Blackjack.':p===d?'Blackjack push.':'Dealer wins Blackjack.');},
 chessMove(){const input=document.getElementById('chess-move'),v=input.value.trim().toLowerCase();try{const move=this.chess.move({from:v.slice(0,2),to:v.slice(2,4),promotion:v[4]||'q'});if(!move)throw Error();MusicSystem.playSFX('board-piece');if(this.chess.isGameOver()){this.finish(this.chess.isCheckmate()?`Checkmate. ${this.chess.turn()==='w'?'Black':'White'} wins.`:'Chess game drawn.');return;}const moves=this.chess.moves();this.chess.move(moves[Math.floor(Math.random()*moves.length)]);this.state.fen=this.chess.fen();this.render();}catch{document.getElementById('hall-status').textContent='Illegal move. Use coordinates such as e2e4.';MusicSystem.playSFX('board-error');}},
 carromStrike(){const angle=Number(document.getElementById('carrom-angle').value),power=Number(document.getElementById('carrom-power').value),chance=Math.max(.1,Math.min(.85,.25+power*.055-Math.abs((angle%45)-22)/100));MusicSystem.playSFX('board-piece');if(Math.random()<chance){this.state.scores[0]++;document.getElementById('hall-status').textContent='Your striker pockets one coin.';}else document.getElementById('hall-status').textContent='The striker misses or rebounds.';if(!this.state.queen&&Math.random()<.08){this.state.queen=true;document.getElementById('hall-status').textContent+=' You pocket the queen.';}if(this.state.scores[0]>=9&&this.state.queen){this.finish('You win Carrom.');return;}if(Math.random()<.45)this.state.scores[1]++;this.render();},
 finish(message){this.state.winner=message;document.getElementById('hall-status').textContent=message;MusicSystem.playSFX('victory');this.render(false);this.syncOnline('finished');},
 render(sync=true){const b=document.getElementById('hall-board'),c=document.getElementById('hall-controls');if(!this.state)return;if(this.type==='snakes'){b.innerHTML=`<p>You: square ${this.state.positions[0]}. Computer: square ${this.state.positions[1]}.</p>`;c.innerHTML=this.state.winner?'':`<button onclick="GameHall.roll()" ${this.state.turn?'disabled':''}>Roll Dice</button>`;}if(this.type==='ludo'){b.innerHTML=`<p>Your tokens: ${this.state.tokens[0].join(', ')}. Computer tokens: ${this.state.tokens[1].join(', ')}. ${this.state.roll!=null?`Rolled ${this.state.roll}.`:''}</p>`;c.innerHTML=this.state.winner?'':this.state.roll==null?`<button onclick="GameHall.roll()" ${this.state.turn?'disabled':''}>Roll Dice</button>`:this.state.tokens[0].map((p,i)=>`<button onclick="GameHall.moveLudo(${i})">Move token ${i+1} from ${p<0?'yard':p}</button>`).join('');}if(this.type==='chess'){b.innerHTML=`<pre aria-label="Chess board">${esc(this.chess.ascii())}</pre>`;c.innerHTML=this.state.winner?'':'<input id="chess-move" placeholder="e2e4" maxlength="5"><button onclick="GameHall.chessMove()">Move</button>';}if(this.type==='carrom'){b.innerHTML=`<p>Your coins: ${this.state.scores[0]}/9. Computer: ${this.state.scores[1]}/9. Queen: ${this.state.queen?'yours':'on board'}.</p>`;c.innerHTML=this.state.winner?'':'<label>Angle 0–359 <input id="carrom-angle" type="number" min="0" max="359" value="45"></label><label>Power 1–10 <input id="carrom-power" type="number" min="1" max="10" value="5"></label><button onclick="GameHall.carromStrike()">Strike</button>';}if(this.type==='blackjack'){b.innerHTML=`<p>Your hand: ${this.state.player.join(', ')} — ${this.handValue(this.state.player)}. Dealer shows ${this.state.done?this.state.dealer.join(', '):this.state.dealer[0]}.</p>`;c.innerHTML=this.state.winner?'':'<button onclick="GameHall.hit()">Hit</button><button onclick="GameHall.stand()">Stand</button>';}if(sync)this.syncOnline();},
 async loadInvites(){if(!OnlineSystem.ready)return;const {data}=await OnlineSystem.client.from('game_hall_invites').select('id,session:game_hall_sessions(id,name,game_type,version,state,status),sender:profiles!game_hall_invites_sender_id_fkey(display_name)').eq('receiver_id',OnlineSystem.user.id).eq('status','pending');const list=document.getElementById('hall-game-list');if(data?.length)list.insertAdjacentHTML('beforeend',data.map(i=>`<button onclick="GameHall.acceptInvite('${i.id}','${i.session.id}')">Accept ${esc(i.session.name)} from ${esc(i.sender?.display_name||'Hero')}</button>`).join(''));},
 async acceptInvite(inviteId,sessionId){await OnlineSystem.client.from('game_hall_invites').update({status:'accepted'}).eq('id',inviteId).eq('receiver_id',OnlineSystem.user.id);const {error}=await OnlineSystem.client.rpc('join_game_hall_session',{sid:sessionId});if(error){Game.addNarrative(error.message,'system');return;}const {data}=await OnlineSystem.client.from('game_hall_sessions').select('*').eq('id',sessionId).single();this.onlineSession=sessionId;this.version=data.version;this.type=data.game_type;this.state=data.state;if(this.type==='chess')this.chess=new Chess(this.state.fen);this.subscribeOnline();this.render(false);Game.addNarrative(`Joined ${data.name}.`,'treasure');},
 async createOnline(){if(!this.type){Game.addNarrative('Select a game first.','system');return;}if(!this.state)this.startLocal();const name=document.getElementById('hall-session-name').value.trim()||`${OnlineSystem.profile.display_name}'s ${this.type}`;const {data,error}=await OnlineSystem.client.rpc('create_game_hall_session',{kind:this.type,session_name:name,players:2,initial_state:this.state});if(error){Game.addNarrative(error.message,'system');return;}this.onlineSession=data;this.version=0;this.subscribeOnline();Game.addNarrative(`Online ${this.type} match created.`,'treasure');},
 async invite(){if(!this.onlineSession){Game.addNarrative('Create an online match first.','system');return;}const target=await OnlineSystem.findProfile(document.getElementById('hall-invite-name').value);if(!target)return;const {error}=await OnlineSystem.client.from('game_hall_invites').insert({session_id:this.onlineSession,sender_id:OnlineSystem.user.id,receiver_id:target.id});Game.addNarrative(error?error.message:`Game invitation sent to ${target.display_name}.`,error?'system':'npc');},
 async syncOnline(status='playing'){if(!this.onlineSession||!this.state)return;const {data,error}=await OnlineSystem.client.rpc('update_game_hall_state',{sid:this.onlineSession,expected_version:this.version,new_state:this.state,new_status:status});if(!error)this.version=data;},
 subscribeOnline(){if(this.subscription)OnlineSystem.client.removeChannel(this.subscription);this.subscription=OnlineSystem.client.channel(`hall-${this.onlineSession}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_hall_sessions',filter:`id=eq.${this.onlineSession}`},p=>{if(p.new.version>this.version){this.version=p.new.version;this.state=p.new.state;if(this.type==='chess')this.chess=new Chess(this.state.fen);this.render(false);}}).subscribe();}
};
GameHall.initWorld();GameHall.inject();window.GameHall=GameHall;
const oldHallCommand=Game.processCommand.bind(Game);Game.processCommand=function(cmd){const c=cmd.toLowerCase().trim();if(c==='game hall'||c==='board games'){GameHall.enterOrOpen();return;}oldHallCommand(cmd);};
