/** Recipient-side realtime chat translation with on-device-first fallback. */
const TranslationService={
    target:(()=>{try{return localStorage.getItem('black_sword_game_language')||'en';}catch(error){return 'en';}})(),cache:new Map(),pending:new Map(),translators:new Map(),logRuns:{direct:0,room:0},maxCacheEntries:200,
    init(){const select=document.getElementById('game-language'),toggle=document.getElementById('auto-translate-chat');if(select){select.value=this.target;select.addEventListener('change',e=>{this.target=e.target.value;localStorage.setItem('black_sword_game_language',this.target);this.status(`Translation language changed to ${select.options[select.selectedIndex].text}.`);window.Game?.showSocial?.({background:true});window.ChatRooms?.renderMessages?.();});}if(toggle){toggle.checked=localStorage.getItem('black_sword_auto_translate')==='true';toggle.addEventListener('change',e=>{localStorage.setItem('black_sword_auto_translate',e.target.checked?'true':'false');if(e.target.checked){window.Game?.showSocial?.({background:true});window.ChatRooms?.renderMessages?.();}});}this.status('Automatic translation is optional and off by default. When enabled, recent messages are translated in a bounded queue.');},
    sourceLanguage(){return this.target;},enabled(){return localStorage.getItem('black_sword_auto_translate')==='true';},status(text){const e=document.getElementById('translation-status');if(e)e.textContent=text;},
    async translate(text,source,target=this.target){source=(source||'en').slice(0,2).toLowerCase();target=(target||'en').slice(0,2).toLowerCase();if(!this.enabled()||source===target||!text)return text;const key=`${source}|${target}|${text}`;if(this.cache.has(key))return this.cache.get(key);if(this.pending.has(key))return this.pending.get(key);
        const task=(async()=>{let translated=null;
            try{if('Translator'in window){const pair=`${source}|${target}`;let translator=this.translators.get(pair);if(!translator){const availability=await Translator.availability({sourceLanguage:source,targetLanguage:target});if(availability!=='unavailable'){translator=await Translator.create({sourceLanguage:source,targetLanguage:target,monitor:m=>m.addEventListener('downloadprogress',e=>this.status(`Downloading private translation model: ${Math.round(e.loaded*100)}%`))});this.translators.set(pair,translator);}}if(translator)translated=await translator.translate(text);}}catch{}
            if(!translated)try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),endpoint='https://black-sold-ultimate.vercel.app/api/translate';try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,450),source,target}),signal:controller.signal});if(response.ok){const data=await response.json();translated=data.text;this.status(`Automatic translation active (${data.provider||'server'}).`);}}finally{clearTimeout(timer);}}catch{}
            translated=translated||text;if(this.cache.size>=this.maxCacheEntries)this.cache.delete(this.cache.keys().next().value);this.cache.set(key,translated);return translated;})();
        this.pending.set(key,task);try{return await task;}finally{this.pending.delete(key);}
    },
    async decorateElement(elementId,text,source,sender='Hero'){const el=document.getElementById(elementId);if(!el)return;const translated=await this.translate(text,source);if(!document.getElementById(elementId))return;const changed=translated!==text;el.innerHTML=`<strong>${Game.escapeHTML(sender)} says:</strong> ${Game.escapeHTML(translated)}${changed?` <small>(${source.slice(0,2)} → ${this.target})</small><details><summary>Original</summary>${Game.escapeHTML(text)}</details>`:''}`;},
    async translateLog(kind,messages,prefix){if(!this.enabled())return;const token=++this.logRuns[kind],recent=(messages||[]).slice(-12);for(const message of recent){if(token!==this.logRuns[kind])return;await this.decorateElement(`${prefix}-${message.id}`,message.body,message.source_language||'en',message.sender?.display_name||'Hero');await new Promise(resolve=>setTimeout(resolve,0));}},
    translateDirectLog(messages){return this.translateLog('direct',messages,'direct-msg');},
    translateRoomLog(messages){return this.translateLog('room',messages,'room-msg');}
};
window.TranslationService=TranslationService;
document.addEventListener('DOMContentLoaded',()=>TranslationService.init());
