/** Recipient-side realtime chat translation with on-device-first fallback. */
const TranslationService={
    target:(()=>{try{return localStorage.getItem('black_sword_game_language')||'en';}catch(error){return 'en';}})(),cache:new Map(),pending:new Map(),translators:new Map(),
    init(){const select=document.getElementById('game-language'),toggle=document.getElementById('auto-translate-chat');if(select){select.value=this.target;select.addEventListener('change',e=>{this.target=e.target.value;localStorage.setItem('black_sword_game_language',this.target);this.status(`Translation language changed to ${select.options[select.selectedIndex].text}.`);window.Game?.showSocial?.();window.ChatRooms?.renderMessages?.();});}if(toggle){toggle.checked=localStorage.getItem('black_sword_auto_translate')!=='false';toggle.addEventListener('change',e=>{localStorage.setItem('black_sword_auto_translate',e.target.checked?'true':'false');});}this.status('Translation uses the browser’s private on-device model when available; otherwise a rate-limited MyMemory fallback is used.');},
    sourceLanguage(){return this.target;},enabled(){return localStorage.getItem('black_sword_auto_translate')!=='false';},status(text){const e=document.getElementById('translation-status');if(e)e.textContent=text;},
    async translate(text,source,target=this.target){source=(source||'en').slice(0,2).toLowerCase();target=(target||'en').slice(0,2).toLowerCase();if(!this.enabled()||source===target||!text)return text;const key=`${source}|${target}|${text}`;if(this.cache.has(key))return this.cache.get(key);if(this.pending.has(key))return this.pending.get(key);
        const task=(async()=>{let translated=null;
            try{if('Translator'in window){const pair=`${source}|${target}`;let translator=this.translators.get(pair);if(!translator){const availability=await Translator.availability({sourceLanguage:source,targetLanguage:target});if(availability!=='unavailable'){translator=await Translator.create({sourceLanguage:source,targetLanguage:target,monitor:m=>m.addEventListener('downloadprogress',e=>this.status(`Downloading private translation model: ${Math.round(e.loaded*100)}%`))});this.translators.set(pair,translator);}}if(translator)translated=await translator.translate(text);}}catch{}
            if(!translated)try{const endpoint=location.protocol==='http:'||location.protocol==='https:'?'/api/translate':'https://black-sold-ultimate.vercel.app/api/translate';const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,450),source,target})});if(response.ok){const data=await response.json();translated=data.text;this.status(`Automatic translation active (${data.provider||'server'}).`);}}catch{}
            translated=translated||text;this.cache.set(key,translated);return translated;})();
        this.pending.set(key,task);try{return await task;}finally{this.pending.delete(key);}
    },
    async decorateElement(elementId,text,source,sender='Hero'){const el=document.getElementById(elementId);if(!el)return;const translated=await this.translate(text,source);if(!document.getElementById(elementId))return;const changed=translated!==text;el.innerHTML=`<strong>${Game.escapeHTML(sender)} says:</strong> ${Game.escapeHTML(translated)}${changed?` <small>(${source.slice(0,2)} → ${this.target})</small><details><summary>Original</summary>${Game.escapeHTML(text)}</details>`:''}`;},
    translateDirectLog(messages){messages.forEach(m=>this.decorateElement(`direct-msg-${m.id}`,m.body,m.source_language||'en',m.sender?.display_name||'Hero'));},
    translateRoomLog(messages){messages.forEach(m=>this.decorateElement(`room-msg-${m.id}`,m.body,m.source_language||'en',m.sender?.display_name||'Hero'));}
};
window.TranslationService=TranslationService;
document.addEventListener('DOMContentLoaded',()=>TranslationService.init());
