import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { setTimeout as wait } from 'node:timers/promises';
import { createRuntime, loadWorld } from '../scripts/load-world.mjs';

const allAchievements=['first-blood','hunter','slayer','peace-1','peace-5','peace-10','level-5','level-10','quest-3','quest-all','hoard','gem','arena-1','arena-5','explorer-20'];
async function ready(t){
    const runtime=await createRuntime();t.after(()=>runtime.dom.window.close());const{window}=runtime,{Game}=window;
    window.OnlineSystem.saveGame=async()=>true;window.OnlineSystem.syncActiveHero=()=>{};window.OnlineSystem.dropWorldItem=async()=>false;window.OnlineSystem.recordGroupAttack=()=>{};
    Game.startNewHero();window.document.getElementById('char-name').value='Fair Audit';window.document.querySelector('.race-btn[data-race="human"]').classList.add('selected');window.document.querySelector('.class-btn[data-class="warrior"]').classList.add('selected');Game.createCharacter(false);
    Game.state.quests=[];Game.state.achievements=[...allAchievements];Game.state.completedQuests=[];window.InterfaceMode.apply('sighted');window.ProfessionalAudioCombat=null;window.AudioManager.endBattle=async()=>{window.AudioManager.battleActive=false;window.AudioManager.overlayMode=null;};window.Math.random=()=>.99;window.GameSpellSystem.random=()=>.99;
    return runtime;
}
const settle=async Game=>{Game.enemyDefeated();for(let i=0;i<30&&!Game.state.battleSummary?.settled;i++)await wait(20);await wait(20);};

// Rewards 1–6
test('(01/37) normal attack does not grant Ruby automatically',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];const before=G.state.player.rubies;G.processCommand('attack');assert.equal(G.state.player.rubies,before);});
test('(02/37) normal attack does not grant Diamond automatically',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];const before=G.state.player.diamonds;G.processCommand('attack');assert.equal(G.state.player.diamonds,before);});
test('(03/37) one victory produces exactly one reward transaction',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];await settle(G);assert.equal(Object.keys(G.state.economy.settledTransactions).length,1);const tx=Object.values(G.state.economy.settledTransactions)[0];assert.equal(tx.gold,G.state.battleSummary.gold);assert.equal(tx.xp,G.state.battleSummary.xp);});
test('(04/37) duplicate victory settlement cannot duplicate rewards',async t=>{const{window}=await ready(t),G=window.Game,summary={id:'duplicate-test',gold:20,xp:30,drops:[],enemyRecords:[{name:'root goblin',xp:30}]};const a=window.RewardEconomy.settleBattle(G,summary,()=>.99),wallet={gold:G.state.player.gold,xp:G.state.player.xp,r:G.state.player.rubies,d:G.state.player.diamonds};const b=window.RewardEconomy.settleBattle(G,summary,()=>0);assert.equal(b.duplicate,true);assert.deepEqual({gold:G.state.player.gold,xp:G.state.player.xp,r:G.state.player.rubies,d:G.state.player.diamonds},wallet);assert.equal(a.id,b.id);});
test('(05/37) common enemies grant configured gold, XP, and no guaranteed premium currency',async t=>{const{window}=await ready(t),G=window.Game,summary={id:'common-test',gold:17,xp:29,drops:[{name:'Bread'}],enemyRecords:[{name:'wolf',xp:29,boss:false}]},before={gold:G.state.player.gold,xp:G.state.player.xp};const result=window.RewardEconomy.settleBattle(G,summary,()=>.99);assert.equal(G.state.player.gold-before.gold,17);assert.equal(G.state.player.xp-before.xp,29);assert.equal(result.premium.ruby,0);assert.equal(result.premium.goldRuby,0);assert.equal(result.premium.diamond,0);assert.equal(result.items.length,1);});
test('(06/37) centralized rarity makes Ruby uncommon and Diamond substantially rarer',async t=>{const{window}=await ready(t),c=window.RewardEconomy.config.tiers;assert.ok(c.common.ruby>0&&c.common.ruby<.05);assert.equal(c.common.diamond,0);assert.ok(c.elite.diamond<c.elite.ruby);assert.ok(c.boss.diamond<c.boss.ruby);assert.ok(c.majorBoss.diamond<c.majorBoss.ruby);assert.ok(window.RewardEconomy.config.rubyPityVictories>=20);});

// Combat 7–12
test('(07/37) combat is world state and never opens a separate battle panel or screen',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');assert.equal(G.state.inCombat,true);assert.equal(G.state.screen,'game-screen');assert.equal(window.document.getElementById('combat-panel').hidden,true);assert.equal(window.document.getElementById('combat-status').classList.contains('hidden'),false);});
test('(08/37) attack works through command input during combat',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];window.Math.random=()=>.5;const enemy=G.state.enemy,hp=enemy.hp;G.processCommand('attack');assert.ok(enemy.hp<hp);});
test('(09/37) attack outside combat is rejected',async t=>{const{window}=await ready(t),G=window.Game;G.state.inCombat=false;window.document.getElementById('narrative').innerHTML='';G.processCommand('attack');assert.equal(G.state.enemy,null);assert.match(window.document.getElementById('narrative').textContent,/not in combat/i);});
test('(10/37) attack outside combat never creates a second enemy',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.processCommand('attack root goblin');assert.equal(G.state.inCombat,false);assert.equal(G.state.enemy,null);});
test('(11/37) repeated and mixed encounter members are aggregated',async t=>{const{window}=await ready(t);assert.equal(window.MonsterGroupFormatter.format(['wild boar','wild boar','goblin witch']),'two wild boars and one goblin witch');});
test('(12/37) victory returns to exploration with no result overlay',async t=>{const{window}=await ready(t),G=window.Game;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];await settle(G);assert.equal(G.state.inCombat,false);assert.equal(window.document.getElementById('combat-status').classList.contains('hidden'),true);assert.equal(G.state.screen,'game-screen');assert.equal(window.document.querySelector('[data-take-everything]'),null);});

// Spells 13–20
test('(13/37) healing validates and consumes mana only for a valid cast',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;p.hp=40;p.maxHp=100;p.mp=50;G.state.spellCooldowns={};const ok=window.GameSpellSystem.castHealing(G);assert.equal(ok,true);assert.ok(p.hp>40);assert.equal(p.mp,36);assert.ok(G.state.spellCooldowns.healing>Date.now());});
test('(14/37) healing fails fairly for full health, unknown spell, and insufficient mana',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;p.hp=p.maxHp;p.mp=50;assert.equal(window.GameSpellSystem.castHealing(G),false);assert.equal(p.mp,50);p.hp=1;p.spells=p.spells.filter(s=>!/heal|mend|supplica|sanctuary|moonwell|remedy|choir/i.test(s));assert.equal(window.GameSpellSystem.castHealing(G),false);assert.equal(p.mp,50);p.spells.push('Minor Heal');p.mp=1;assert.equal(window.GameSpellSystem.castHealing(G),false);assert.equal(p.mp,1);});
test('(15/37) Multiple Strike validates combat, targets, mana, and cooldown',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];p.mp=50;G.state.spellCooldowns={};G.state.enemy.hp=G.state.enemy.maxHp=500;const hp=G.state.enemy.hp;assert.equal(window.GameSpellSystem.castMultipleStrike(G),true);assert.ok(G.state.enemy.hp<hp);assert.equal(p.mp,32);assert.ok(G.state.spellCooldowns.multipleStrike>Date.now());});
test('(16/37) Multiple Strike can fail after a valid paid cast and explains recovery',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];p.mp=50;G.state.spellCooldowns={};window.GameSpellSystem.random=()=>0;assert.equal(window.GameSpellSystem.castMultipleStrike(G),false);assert.equal(p.mp,32);assert.match(window.document.getElementById('narrative').textContent,/fails after using/i);assert.equal(window.GameSpellSystem.castMultipleStrike(G),false);assert.match(window.document.getElementById('narrative').textContent,/recovering/i);});
test('(17/37) Opening Doors affects only its compatible magical door',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;G.state.location='drakkar_keep_2';p.mp=50;G.state.spellCooldowns={};const door=window.WorldData.locations.drakkar_keep_2.specialDoor,reverse=window.WorldData.locations.drakkar_keep_3.specialDoor;assert.ok(door.magical&&reverse.magical);assert.equal(reverse.destination,'drakkar_keep_2');assert.equal(window.GameSpellSystem.castOpeningDoors(G),true);assert.equal(G.state.specialDoors[door.id].open,true);assert.equal(window.WorldData.locations[door.location].exits[door.direction],door.destination);assert.equal(window.WorldData.locations[reverse.location].exits[reverse.direction],reverse.destination);assert.equal(p.mp,42);});
test('(18/37) an already-open magical door rejects Opening Doors without mana cost',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;G.state.location='drakkar_keep_2';p.mp=50;G.state.spellCooldowns={};assert.equal(window.GameSpellSystem.castOpeningDoors(G),true);G.state.spellCooldowns.openingDoors=0;const before=p.mp;assert.equal(window.GameSpellSystem.castOpeningDoors(G),false);assert.equal(p.mp,before);assert.match(window.document.getElementById('narrative').textContent,/already open/i);});
test('(19/37) non-door locations reject Opening Doors without consuming mana',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;G.state.location='kaliwasch';p.mp=50;assert.equal(window.GameSpellSystem.castOpeningDoors(G),false);assert.equal(p.mp,50);assert.match(window.document.getElementById('narrative').textContent,/no magical door/i);});
test('(20/37) Multiple Strike breaks only a door explicitly configured for it',async t=>{const{window}=await ready(t),G=window.Game,p=G.state.player;p.mp=60;G.state.location='public_house_kaliwasch_1_door';assert.equal(window.GameSpellSystem.castMultipleStrike(G),false);assert.equal(p.mp,60);G.state.location='drakkar_keep_2';G.state.spellCooldowns={};const door=window.WorldData.locations.drakkar_keep_2.specialDoor;assert.equal(door.canBeBrokenByMultipleStrike,true);assert.equal(window.GameSpellSystem.castMultipleStrike(G),true);assert.equal(G.state.specialDoors[door.id].method,'multiple-strike');});

// World 21–25
let worldFixture;test.before(async()=>{worldFixture=await loadWorld();});
const route=(locations,start,target)=>{const q=[[start,[]]],seen=new Set([start]);while(q.length){const[id,path]=q.shift();if(id===target)return path;for(const[d,next]of Object.entries(locations[id]?.exits||{}))if(!seen.has(next)){seen.add(next);q.push([next,[...path,d]]);}}return null;};
test('(21/37) Forest Entrance is reachable on the live graph',()=>assert.ok(route(worldFixture.world.locations,'kaliwasch','great_forest_east_gate')?.length));
test('(22/37) City Directory identifies an executable live Forest Entrance route',async t=>{const{window}=await ready(t),G=window.Game;assert.equal(window.CityDirectory.cities[0].targets.forest_entrance,'great_forest_east_gate');const path=G.findPhysicalRoute('kaliwasch','great_forest_east_gate');assert.ok(path?.length);let id='kaliwasch';for(const d of path)id=window.WorldData.locations[id].exits[d];assert.equal(id,'great_forest_east_gate');});
test('(23/37) random wilderness battles remain possible after quest completion',async t=>{const{window}=await ready(t),G=window.Game,L=window.WorldData.locations.forest;G.state.slainEnemies.forest=Object.fromEntries(L.enemies.map(name=>[name,999]));assert.ok(G.getRandomEncounterPool('forest').length);});
test('(24/37) encounter cooldown blocks movement spam',async t=>{const{window}=await ready(t),G=window.Game;G.state.sacred.movesSinceEncounter=99;G.state.sacred.lastRandomEncounterAt=100000;assert.equal(G.randomEncounterEligibility('forest',120000).eligible,false);assert.equal(G.randomEncounterEligibility('forest',146000).eligible,true);});
test('(25/37) only one cooldown-controlled wilderness scheduler remains',async()=>{const [black,sacred]=await Promise.all([readFile('black-sword-alexa-multiplayer-v26.js','utf8'),readFile('sacred.js','utf8')]);assert.doesNotMatch(black,/setTimeout\(\(\) => \{\s*if \(!this\.state\.inCombat\) this\.startCombat/);assert.match(sacred,/encounterNonce/);assert.match(sacred,/randomEncounterEligibility/);});

// TTS 26–29
test('(26/37) encounter game TTS fires exactly once',async t=>{const{window}=await ready(t),G=window.Game,spoken=[];window.AudioManager.playVoice=async text=>(spoken.push(text),true);G.state.location='forest';G.startCombat('root goblin');await wait(0);assert.equal(spoken.filter(t=>/^You encountered /.test(t)).length,1);});
test('(27/37) victory game TTS fires exactly once',async t=>{const{window}=await ready(t),G=window.Game,spoken=[];window.AudioManager.playVoice=async text=>(spoken.push(text),true);G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];await settle(G);assert.equal(spoken.filter(t=>/^You defeated /.test(t)).length,1);});
test('(28/37) reward game TTS fires exactly once',async t=>{const{window}=await ready(t),G=window.Game,spoken=[];window.AudioManager.playVoice=async text=>(spoken.push(text),true);G.state.location='forest';G.startCombat('root goblin');G.state.sacred.enemyQueue=[];await settle(G);assert.equal(spoken.filter(t=>/^Rewards: /.test(t)).length,1);});
test('(29/37) critical TTS delegates to the centralized queue as critical',async t=>{const{window}=await ready(t),seen=[];window.AudioManager.playVoice=async(text,options)=>(seen.push({text,options}),true);await window.AudioManager.speakCritical('critical audit');assert.equal(seen.length,1);assert.equal(seen[0].options.priority,'critical');});

// Chat / feedback 30–33
test('(30/37) five-minute server expiration remains exact and immutable',async()=>{const sql=await readFile('supabase/features_v18_five_minute_chat.sql','utf8');assert.match(sql,/new\.expires_at=new\.created_at\+interval '5 minutes'/);assert.match(sql,/timestamps are immutable/i);});
test('(31/37) expired messages are excluded by server RLS and client queries',async()=>{const [sql,online,rooms,translation]=await Promise.all([readFile('supabase/features_v18_five_minute_chat.sql','utf8'),readFile('online.js','utf8'),readFile('chat-rooms.js','utf8'),readFile('translation.js','utf8')]);assert.match(sql,/expires_at>now\(\)/);assert.match(online,/\.gt\('expires_at'/);assert.match(rooms,/\.gt\('expires_at'/);assert.match(rooms,/isFresh/);assert.match(rooms,/\.limit\(50\)/);assert.match(rooms,/appendMessage\(message\)/);assert.match(online,/socialRefreshInFlight/);assert.match(online,/socialRefreshTimer=setTimeout/);assert.match(translation,/\.slice\(-12\)/);assert.match(translation,/maxCacheEntries:200/);assert.match(translation,/black_sword_auto_translate'\)==='true'/);});
test('(32/37) feedback submits through the protected database RPC',async t=>{const{window}=await ready(t),calls=[];window.OnlineSystem.ready=true;window.OnlineSystem.user={id:'user'};window.OnlineSystem.client={rpc:async(name,args)=>(calls.push({name,args}),{data:'00000000-0000-0000-0000-000000000001',error:null})};assert.equal(await window.OnlineSystem.sendFeedback('accessibility','Game TTS did not speak.'),true);assert.equal(calls[0].name,'submit_game_feedback');assert.equal(calls[0].args.feedback_category,'accessibility');});
test('(33/37) feedback reaches only an authorized moderator/developer inbox',async()=>{const sql=await readFile('supabase/features_v19_feedback_moderation.sql','utf8');assert.match(sql,/moderator_roles/);assert.match(sql,/if not is_game_moderator\(\) then raise exception 'Not authorized for moderator inbox'/);assert.match(sql,/resolution_note is 'Private moderator\/developer note/i);assert.match(sql,/revoke all on public\.moderator_roles from anon,authenticated/i);assert.match(sql,/assign_game_feedback/);});

// Accessibility 34–37
test('(34/37) Blind/TalkBack-first mode keeps command-first semantic controls',async t=>{const{window}=await ready(t),d=window.document;window.InterfaceMode.apply('blind');assert.equal(d.documentElement.dataset.interfaceMode,'blind');assert.ok(d.getElementById('cmd-input').getAttribute('aria-label'));assert.equal(d.getElementById('narrative').getAttribute('role'),'log');assert.equal(d.getElementById('room-message-log').getAttribute('role'),'log');assert.match(d.getElementById('room-message-log').getAttribute('aria-relevant'),/additions/);const controls=[...d.querySelectorAll('input:not([type="hidden"]),select,textarea')],unlabeled=controls.filter(e=>!(e.getAttribute('aria-label')||e.getAttribute('aria-labelledby')||e.getAttribute('title')||(e.id&&d.querySelector(`label[for="${e.id}"]`))||e.closest('label')||['button','submit','reset'].includes(e.type))).map(e=>e.id);assert.deepEqual(unlabeled,[]);});
test('(35/37) Sighted mode uses the same game state and exposes inline combat information',async t=>{const{window}=await ready(t),G=window.Game;window.InterfaceMode.apply('sighted');G.state.location='forest';G.startCombat('root goblin');assert.equal(window.document.documentElement.dataset.interfaceMode,'sighted');assert.match(window.document.getElementById('combat-status-text').textContent,/Fighting|Encounter:/);assert.equal(window.document.getElementById('combat-panel').hidden,true);});
test('(36/37) command input remains accessible after encounter TTS completes',async t=>{const{window}=await ready(t),G=window.Game;window.AudioManager.playVoice=async()=>true;G.state.location='forest';G.startCombat('root goblin');await wait(0);const input=window.document.getElementById('cmd-input');assert.equal(input.disabled,false);assert.ok(input.getAttribute('aria-label'));});
test('(37/37) duplicate event IDs cannot repeat live-region or game-TTS announcements',async t=>{const{window}=await ready(t),G=window.Game,spoken=[];window.AudioManager.playVoice=async text=>(spoken.push(text),true);window.document.getElementById('narrative').innerHTML='';await G.emitGameEvent('One clear announcement.','combat',{eventId:'same-event'});await G.emitGameEvent('One clear announcement.','combat',{eventId:'same-event'});assert.equal(spoken.length,1);assert.equal([...window.document.querySelectorAll('#narrative p')].filter(p=>p.textContent==='One clear announcement.').length,1);});
